export interface CityInfo {
  name: string;
  longitude: number; // degrees East
}

export interface ProvinceInfo {
  name: string;
  cities: CityInfo[];
}

export const PROVINCES: ProvinceInfo[] = [
  // ─── 直辖市 ───────────────────────────────────────────
  {
    name: '北京市',
    cities: [{ name: '北京', longitude: 116.4 }],
  },
  {
    name: '天津市',
    cities: [{ name: '天津', longitude: 117.2 }],
  },
  {
    name: '上海市',
    cities: [{ name: '上海', longitude: 121.5 }],
  },
  {
    name: '重庆市',
    cities: [
      { name: '重庆', longitude: 106.6 },
      { name: '万州', longitude: 108.4 },
      { name: '涪陵', longitude: 107.4 },
      { name: '黔江', longitude: 108.8 },
    ],
  },

  // ─── 华北 ─────────────────────────────────────────────
  {
    name: '河北省',
    cities: [
      { name: '石家庄', longitude: 114.5 },
      { name: '保定', longitude: 115.5 },
      { name: '唐山', longitude: 118.2 },
      { name: '秦皇岛', longitude: 119.6 },
      { name: '廊坊', longitude: 116.7 },
      { name: '张家口', longitude: 114.9 },
      { name: '承德', longitude: 117.9 },
      { name: '沧州', longitude: 116.8 },
      { name: '邯郸', longitude: 114.5 },
      { name: '衡水', longitude: 115.7 },
      { name: '邢台', longitude: 114.5 },
    ],
  },
  {
    name: '山西省',
    cities: [
      { name: '太原', longitude: 112.6 },
      { name: '大同', longitude: 113.3 },
      { name: '长治', longitude: 113.1 },
      { name: '晋城', longitude: 112.9 },
      { name: '朔州', longitude: 112.4 },
      { name: '晋中', longitude: 112.8 },
      { name: '运城', longitude: 111.0 },
      { name: '忻州', longitude: 112.7 },
      { name: '临汾', longitude: 111.5 },
      { name: '吕梁', longitude: 111.1 },
    ],
  },
  {
    name: '内蒙古自治区',
    cities: [
      { name: '呼和浩特', longitude: 111.7 },
      { name: '包头', longitude: 110.0 },
      { name: '鄂尔多斯', longitude: 109.8 },
      { name: '赤峰', longitude: 118.9 },
      { name: '通辽', longitude: 122.3 },
      { name: '呼伦贝尔', longitude: 119.7 },
      { name: '乌兰察布', longitude: 113.1 },
      { name: '巴彦淖尔', longitude: 107.4 },
      { name: '锡林郭勒', longitude: 116.1 },
    ],
  },

  // ─── 东北 ─────────────────────────────────────────────
  {
    name: '辽宁省',
    cities: [
      { name: '沈阳', longitude: 123.4 },
      { name: '大连', longitude: 121.6 },
      { name: '鞍山', longitude: 122.9 },
      { name: '抚顺', longitude: 123.9 },
      { name: '本溪', longitude: 123.8 },
      { name: '丹东', longitude: 124.4 },
      { name: '锦州', longitude: 121.1 },
      { name: '营口', longitude: 122.2 },
      { name: '阜新', longitude: 121.7 },
      { name: '辽阳', longitude: 123.2 },
      { name: '朝阳', longitude: 120.5 },
      { name: '盘锦', longitude: 122.1 },
      { name: '葫芦岛', longitude: 120.8 },
    ],
  },
  {
    name: '吉林省',
    cities: [
      { name: '长春', longitude: 125.4 },
      { name: '吉林', longitude: 126.6 },
      { name: '四平', longitude: 124.4 },
      { name: '辽源', longitude: 125.1 },
      { name: '通化', longitude: 125.9 },
      { name: '白山', longitude: 126.4 },
      { name: '松原', longitude: 124.8 },
      { name: '白城', longitude: 122.8 },
      { name: '延边', longitude: 129.5 },
    ],
  },
  {
    name: '黑龙江省',
    cities: [
      { name: '哈尔滨', longitude: 126.5 },
      { name: '齐齐哈尔', longitude: 123.9 },
      { name: '牡丹江', longitude: 129.6 },
      { name: '佳木斯', longitude: 130.4 },
      { name: '大庆', longitude: 125.0 },
      { name: '绥化', longitude: 126.9 },
      { name: '鸡西', longitude: 130.9 },
      { name: '双鸭山', longitude: 131.2 },
      { name: '伊春', longitude: 128.9 },
      { name: '七台河', longitude: 130.8 },
      { name: '鹤岗', longitude: 130.3 },
      { name: '黑河', longitude: 127.5 },
    ],
  },

  // ─── 华东 ─────────────────────────────────────────────
  {
    name: '江苏省',
    cities: [
      { name: '南京', longitude: 118.8 },
      { name: '苏州', longitude: 120.6 },
      { name: '无锡', longitude: 120.3 },
      { name: '常州', longitude: 119.9 },
      { name: '南通', longitude: 120.9 },
      { name: '扬州', longitude: 119.4 },
      { name: '徐州', longitude: 117.2 },
      { name: '连云港', longitude: 119.2 },
      { name: '淮安', longitude: 119.0 },
      { name: '盐城', longitude: 120.2 },
      { name: '镇江', longitude: 119.5 },
      { name: '泰州', longitude: 119.9 },
      { name: '宿迁', longitude: 118.3 },
    ],
  },
  {
    name: '浙江省',
    cities: [
      { name: '杭州', longitude: 120.1 },
      { name: '宁波', longitude: 121.6 },
      { name: '温州', longitude: 120.7 },
      { name: '嘉兴', longitude: 120.8 },
      { name: '湖州', longitude: 120.1 },
      { name: '绍兴', longitude: 120.6 },
      { name: '金华', longitude: 119.6 },
      { name: '衢州', longitude: 118.9 },
      { name: '舟山', longitude: 122.1 },
      { name: '台州', longitude: 121.4 },
      { name: '丽水', longitude: 119.9 },
    ],
  },
  {
    name: '安徽省',
    cities: [
      { name: '合肥', longitude: 117.3 },
      { name: '芜湖', longitude: 118.4 },
      { name: '蚌埠', longitude: 117.4 },
      { name: '淮南', longitude: 117.0 },
      { name: '马鞍山', longitude: 118.5 },
      { name: '淮北', longitude: 116.8 },
      { name: '铜陵', longitude: 117.8 },
      { name: '安庆', longitude: 117.1 },
      { name: '黄山', longitude: 118.3 },
      { name: '滁州', longitude: 118.3 },
      { name: '阜阳', longitude: 115.8 },
      { name: '宿州', longitude: 116.9 },
      { name: '六安', longitude: 116.5 },
      { name: '亳州', longitude: 115.8 },
    ],
  },
  {
    name: '福建省',
    cities: [
      { name: '福州', longitude: 119.3 },
      { name: '厦门', longitude: 118.1 },
      { name: '莆田', longitude: 119.0 },
      { name: '三明', longitude: 117.6 },
      { name: '泉州', longitude: 118.7 },
      { name: '漳州', longitude: 117.6 },
      { name: '南平', longitude: 118.2 },
      { name: '龙岩', longitude: 117.0 },
      { name: '宁德', longitude: 119.5 },
    ],
  },
  {
    name: '江西省',
    cities: [
      { name: '南昌', longitude: 115.9 },
      { name: '景德镇', longitude: 117.2 },
      { name: '萍乡', longitude: 113.9 },
      { name: '九江', longitude: 116.0 },
      { name: '新余', longitude: 114.9 },
      { name: '鹰潭', longitude: 117.1 },
      { name: '赣州', longitude: 114.9 },
      { name: '吉安', longitude: 114.9 },
      { name: '宜春', longitude: 114.4 },
      { name: '抚州', longitude: 116.4 },
      { name: '上饶', longitude: 117.9 },
    ],
  },
  {
    name: '山东省',
    cities: [
      { name: '济南', longitude: 117.0 },
      { name: '青岛', longitude: 120.4 },
      { name: '淄博', longitude: 118.1 },
      { name: '枣庄', longitude: 117.6 },
      { name: '东营', longitude: 118.7 },
      { name: '烟台', longitude: 121.4 },
      { name: '潍坊', longitude: 119.1 },
      { name: '济宁', longitude: 116.6 },
      { name: '泰安', longitude: 117.1 },
      { name: '威海', longitude: 122.1 },
      { name: '日照', longitude: 119.5 },
      { name: '临沂', longitude: 118.4 },
      { name: '德州', longitude: 116.4 },
      { name: '聊城', longitude: 116.0 },
      { name: '滨州', longitude: 118.0 },
      { name: '菏泽', longitude: 115.5 },
    ],
  },

  // ─── 华中 ─────────────────────────────────────────────
  {
    name: '河南省',
    cities: [
      { name: '郑州', longitude: 113.6 },
      { name: '开封', longitude: 114.3 },
      { name: '洛阳', longitude: 112.5 },
      { name: '平顶山', longitude: 113.3 },
      { name: '安阳', longitude: 114.4 },
      { name: '鹤壁', longitude: 114.3 },
      { name: '新乡', longitude: 113.9 },
      { name: '焦作', longitude: 113.2 },
      { name: '濮阳', longitude: 115.0 },
      { name: '许昌', longitude: 113.8 },
      { name: '漯河', longitude: 114.0 },
      { name: '三门峡', longitude: 111.2 },
      { name: '南阳', longitude: 112.5 },
      { name: '商丘', longitude: 115.6 },
      { name: '信阳', longitude: 114.1 },
      { name: '周口', longitude: 114.7 },
      { name: '驻马店', longitude: 114.0 },
    ],
  },
  {
    name: '湖北省',
    cities: [
      { name: '武汉', longitude: 114.3 },
      { name: '黄石', longitude: 115.0 },
      { name: '十堰', longitude: 110.8 },
      { name: '宜昌', longitude: 111.3 },
      { name: '襄阳', longitude: 112.1 },
      { name: '鄂州', longitude: 114.9 },
      { name: '荆门', longitude: 112.2 },
      { name: '孝感', longitude: 113.9 },
      { name: '荆州', longitude: 112.2 },
      { name: '黄冈', longitude: 114.9 },
      { name: '咸宁', longitude: 114.3 },
      { name: '随州', longitude: 113.4 },
      { name: '恩施', longitude: 109.5 },
    ],
  },
  {
    name: '湖南省',
    cities: [
      { name: '长沙', longitude: 113.0 },
      { name: '株洲', longitude: 113.1 },
      { name: '湘潭', longitude: 112.9 },
      { name: '衡阳', longitude: 112.6 },
      { name: '邵阳', longitude: 111.5 },
      { name: '岳阳', longitude: 113.1 },
      { name: '常德', longitude: 111.7 },
      { name: '张家界', longitude: 110.5 },
      { name: '益阳', longitude: 112.4 },
      { name: '郴州', longitude: 113.0 },
      { name: '永州', longitude: 111.6 },
      { name: '怀化', longitude: 110.0 },
      { name: '娄底', longitude: 112.0 },
      { name: '湘西', longitude: 109.7 },
    ],
  },

  // ─── 华南 ─────────────────────────────────────────────
  {
    name: '广东省',
    cities: [
      { name: '广州', longitude: 113.3 },
      { name: '深圳', longitude: 114.1 },
      { name: '珠海', longitude: 113.6 },
      { name: '佛山', longitude: 113.1 },
      { name: '东莞', longitude: 113.8 },
      { name: '中山', longitude: 113.4 },
      { name: '江门', longitude: 113.1 },
      { name: '惠州', longitude: 114.4 },
      { name: '汕头', longitude: 116.7 },
      { name: '湛江', longitude: 110.4 },
      { name: '茂名', longitude: 110.9 },
      { name: '肇庆', longitude: 112.5 },
      { name: '梅州', longitude: 116.1 },
      { name: '韶关', longitude: 113.6 },
      { name: '阳江', longitude: 111.9 },
      { name: '清远', longitude: 113.1 },
      { name: '潮州', longitude: 116.6 },
      { name: '揭阳', longitude: 116.4 },
      { name: '云浮', longitude: 112.0 },
    ],
  },
  {
    name: '广西壮族自治区',
    cities: [
      { name: '南宁', longitude: 108.3 },
      { name: '柳州', longitude: 109.4 },
      { name: '桂林', longitude: 110.3 },
      { name: '梧州', longitude: 111.3 },
      { name: '北海', longitude: 109.1 },
      { name: '防城港', longitude: 108.4 },
      { name: '钦州', longitude: 108.6 },
      { name: '贵港', longitude: 109.6 },
      { name: '玉林', longitude: 110.2 },
      { name: '百色', longitude: 106.6 },
      { name: '贺州', longitude: 111.6 },
      { name: '河池', longitude: 108.1 },
      { name: '来宾', longitude: 109.2 },
      { name: '崇左', longitude: 107.4 },
    ],
  },
  {
    name: '海南省',
    cities: [
      { name: '海口', longitude: 110.3 },
      { name: '三亚', longitude: 109.5 },
      { name: '儋州', longitude: 109.6 },
      { name: '文昌', longitude: 110.8 },
      { name: '琼海', longitude: 110.5 },
      { name: '万宁', longitude: 110.4 },
      { name: '陵水', longitude: 110.0 },
      { name: '乐东', longitude: 109.2 },
      { name: '五指山', longitude: 109.5 },
    ],
  },

  // ─── 西南 ─────────────────────────────────────────────
  {
    name: '四川省',
    cities: [
      { name: '成都', longitude: 104.1 },
      { name: '绵阳', longitude: 104.7 },
      { name: '德阳', longitude: 104.4 },
      { name: '宜宾', longitude: 104.6 },
      { name: '泸州', longitude: 105.4 },
      { name: '达州', longitude: 107.5 },
      { name: '南充', longitude: 106.1 },
      { name: '乐山', longitude: 103.8 },
      { name: '自贡', longitude: 104.8 },
      { name: '攀枝花', longitude: 101.7 },
      { name: '遂宁', longitude: 105.6 },
      { name: '内江', longitude: 105.1 },
      { name: '广元', longitude: 105.8 },
      { name: '雅安', longitude: 103.0 },
      { name: '巴中', longitude: 106.8 },
      { name: '资阳', longitude: 104.6 },
      { name: '广安', longitude: 106.6 },
      { name: '眉山', longitude: 103.8 },
      { name: '凉山', longitude: 102.3 },
      { name: '甘孜', longitude: 101.9 },
      { name: '阿坝', longitude: 102.2 },
    ],
  },
  {
    name: '贵州省',
    cities: [
      { name: '贵阳', longitude: 106.7 },
      { name: '遵义', longitude: 106.9 },
      { name: '六盘水', longitude: 104.8 },
      { name: '安顺', longitude: 105.9 },
      { name: '毕节', longitude: 105.3 },
      { name: '铜仁', longitude: 109.2 },
      { name: '黔西南', longitude: 104.9 },
      { name: '黔东南', longitude: 107.9 },
      { name: '黔南', longitude: 107.5 },
    ],
  },
  {
    name: '云南省',
    cities: [
      { name: '昆明', longitude: 102.7 },
      { name: '曲靖', longitude: 103.8 },
      { name: '玉溪', longitude: 102.5 },
      { name: '保山', longitude: 99.2 },
      { name: '昭通', longitude: 103.7 },
      { name: '丽江', longitude: 100.2 },
      { name: '普洱', longitude: 101.0 },
      { name: '临沧', longitude: 100.1 },
      { name: '楚雄', longitude: 101.5 },
      { name: '红河', longitude: 103.5 },
      { name: '文山', longitude: 104.2 },
      { name: '西双版纳', longitude: 100.8 },
      { name: '大理', longitude: 100.2 },
      { name: '德宏', longitude: 98.6 },
      { name: '怒江', longitude: 98.8 },
      { name: '迪庆', longitude: 99.7 },
    ],
  },
  {
    name: '西藏自治区',
    cities: [
      { name: '拉萨', longitude: 91.1 },
      { name: '日喀则', longitude: 88.9 },
      { name: '昌都', longitude: 97.2 },
      { name: '林芝', longitude: 94.4 },
      { name: '山南', longitude: 91.8 },
      { name: '那曲', longitude: 92.1 },
      { name: '阿里', longitude: 80.1 },
    ],
  },

  // ─── 西北 ─────────────────────────────────────────────
  {
    name: '陕西省',
    cities: [
      { name: '西安', longitude: 108.9 },
      { name: '咸阳', longitude: 108.7 },
      { name: '宝鸡', longitude: 107.2 },
      { name: '铜川', longitude: 109.1 },
      { name: '渭南', longitude: 109.5 },
      { name: '延安', longitude: 109.5 },
      { name: '汉中', longitude: 107.1 },
      { name: '榆林', longitude: 109.7 },
      { name: '安康', longitude: 109.0 },
      { name: '商洛', longitude: 109.9 },
    ],
  },
  {
    name: '甘肃省',
    cities: [
      { name: '兰州', longitude: 103.8 },
      { name: '嘉峪关', longitude: 98.3 },
      { name: '金昌', longitude: 102.2 },
      { name: '白银', longitude: 104.2 },
      { name: '天水', longitude: 105.7 },
      { name: '武威', longitude: 102.6 },
      { name: '张掖', longitude: 100.5 },
      { name: '平凉', longitude: 106.7 },
      { name: '酒泉', longitude: 98.5 },
      { name: '庆阳', longitude: 107.6 },
      { name: '定西', longitude: 104.6 },
      { name: '陇南', longitude: 104.9 },
      { name: '临夏', longitude: 103.2 },
      { name: '甘南', longitude: 102.9 },
    ],
  },
  {
    name: '青海省',
    cities: [
      { name: '西宁', longitude: 101.8 },
      { name: '海东', longitude: 102.1 },
      { name: '格尔木', longitude: 94.9 },
      { name: '德令哈', longitude: 97.4 },
      { name: '玉树', longitude: 97.0 },
      { name: '果洛', longitude: 100.2 },
      { name: '海西', longitude: 97.4 },
    ],
  },
  {
    name: '宁夏回族自治区',
    cities: [
      { name: '银川', longitude: 106.3 },
      { name: '石嘴山', longitude: 106.4 },
      { name: '吴忠', longitude: 106.2 },
      { name: '固原', longitude: 106.3 },
      { name: '中卫', longitude: 105.2 },
    ],
  },
  {
    name: '新疆维吾尔自治区',
    cities: [
      { name: '乌鲁木齐', longitude: 87.6 },
      { name: '克拉玛依', longitude: 84.9 },
      { name: '吐鲁番', longitude: 89.2 },
      { name: '哈密', longitude: 93.5 },
      { name: '昌吉', longitude: 87.3 },
      { name: '博尔塔拉', longitude: 82.1 },
      { name: '巴音郭楞', longitude: 86.2 },
      { name: '阿克苏', longitude: 80.3 },
      { name: '克孜勒苏', longitude: 76.2 },
      { name: '喀什', longitude: 75.9 },
      { name: '和田', longitude: 79.9 },
      { name: '伊犁', longitude: 81.3 },
      { name: '塔城', longitude: 83.0 },
      { name: '阿勒泰', longitude: 88.1 },
      { name: '石河子', longitude: 86.1 },
    ],
  },
];
