/**
 * 人纪 — 倪海厦中医经典教学体系数据库
 *
 * 「中知人事」—— 人之纪，是中医经典的体系化教学。
 * 2004-2005年完成，包含五大中医经典课程。
 * 学习顺序：针灸 → 黄帝内经 → 神农本草经 → 伤寒论 → 金匮要略
 *
 * 核心理念：
 *   中医是物理医学，从物理的角度分析人的身体。
 *   学成者可从感冒治疗至肝癌。
 */

import type { NiModule, AcuExperience, TransNeedling, HantangFormula, ClassicFormula } from './types';

// ─── 人纪模块 ────────────────────────────────────────────
export const RENJI_MODULES: NiModule[] = [
  {
    id: 'rj-zhenjiu',
    category: 'renji',
    name: '针灸大成',
    nameEn: 'Zhen Jiu Da Cheng',
    subtitle: '人纪第一课 · 经络穴位',
    description: '针灸是人纪的入门课程，依据《针灸甲乙经》和《针灸大成》讲授。通过经络穴位的学习，建立对人体气血运行的基本认知。',
    details: [
      '针灸课是人纪系列的第一门课，也是中医入门的基础。倪师强调，不懂经络穴位就无法理解中医的诊断与治疗。',
      '课程依据《针灸甲乙经》和《针灸大成》两部经典编写，系统讲解十二正经、奇经八脉的循行路线与主要穴位。',
      '倪师的针灸教学注重实战，每个穴位都有具体的临床应用说明，而非纯粹的理论记忆。',
      '倪师认为针灸是「最快速的治疗手段」，许多急症可以通过针灸迅速缓解。',
    ],
    lessons: '44集（每集约44分钟）',
    references: [
      '《针灸甲乙经》',
      '《针灸大成》',
      '倪海厦《人纪·针灸》讲义',
    ],
    keywords: ['针灸', '经络', '穴位', '十二正经', '奇经八脉', '针灸大成', '针灸甲乙经'],
    icon: '⊕',
    status: 'active',
    order: 1,
    slug: 'zhenjiu',
    chapters: [
      {
        id: 'rj-zj-01',
        title: '经络总论',
        subtitle: '十二正经与奇经八脉',
        description: '人体经络系统的整体框架，十二正经的循行路线与奇经八脉的特殊功能。',
        keyPoints: [
          '十二正经：手三阴、手三阳、足三阴、足三阳',
          '奇经八脉：任、督、冲、带、阴维、阳维、阴跷、阳跷',
          '经络的气血流注时间（子午流注）',
          '经络与脏腑的表里关系',
        ],
        order: 1,
      },
      {
        id: 'rj-zj-02',
        title: '重要穴位详解',
        subtitle: '临床常用穴位与配伍',
        description: '临床最常用的穴位定位、取穴方法与针刺技巧，以及常见病症的穴位配伍。',
        keyPoints: [
          '五输穴（井荥输经合）的运用',
          '原穴、络穴、俞穴、募穴的区别',
          '特殊穴位：百会、合谷、足三里、三阴交等',
          '补泻手法：提插补泻、捻转补泻',
        ],
        order: 2,
      },
      {
        id: 'rj-zj-03',
        title: '针灸治疗实战',
        subtitle: '常见病症的针灸方案',
        description: '从头痛到腰痛，从感冒到失眠，覆盖常见病症的针灸治疗方案。',
        keyPoints: [
          '头痛：不同经络的头痛对应不同穴位',
          '腰痛：委中、肾俞、大肠俞的运用',
          '急症：中风急救的针灸方法',
          '内科：失眠、消化不良、月经不调等',
        ],
        order: 3,
      },
    ],
  },
  {
    id: 'rj-neijing',
    category: 'renji',
    name: '黄帝内经',
    nameEn: 'Huang Di Nei Jing',
    subtitle: '人纪第二课 · 中医理论根基',
    description: '《黄帝内经》是中医的理论根基，倪师通过讲解《素问》和《灵枢》，建立完整的中医哲学与诊断体系。',
    details: [
      '《黄帝内经》分为《素问》和《灵枢》两部分，是中医理论的最高经典。',
      '倪师的讲解不是逐字翻译，而是将古文智慧转化为可操作的临床知识。',
      '核心内容包括阴阳五行理论、脏腑学说、病因病机、诊断方法等。',
      '倪师特别强调「形神合一」的概念——中医不仅治病，更关注整体生命状态。',
    ],
    lessons: '20集（每集约1小时）',
    references: [
      '《黄帝内经·素问》',
      '《黄帝内经·灵枢》',
      '倪海厦《人纪·黄帝内经》讲义',
    ],
    keywords: ['黄帝内经', '素问', '灵枢', '阴阳', '五行', '脏腑', '病因病机', '形神'],
    icon: '☯',
    status: 'active',
    order: 2,
    slug: 'neijing',
    chapters: [
      {
        id: 'rj-nj-01',
        title: '阴阳五行',
        subtitle: '中医哲学基础',
        description: '阴阳对立统一与五行生克制化的基本理论，是理解中医一切诊断治疗的基础。',
        keyPoints: [
          '阴阳的基本特征与相互关系',
          '五行（木火土金水）的生克关系',
          '五行与脏腑的对应：肝木、心火、脾土、肺金、肾水',
          '五行在诊断和治疗中的应用',
        ],
        order: 1,
      },
      {
        id: 'rj-nj-02',
        title: '脏腑学说',
        subtitle: '五脏六腑的功能与关系',
        description: '五脏（肝心脾肺肾）和六腑（胆小肠胃大肠膀胱三焦）的生理功能与相互关系。',
        keyPoints: [
          '五脏藏精气、六腑传化水谷',
          '脏腑表里关系：肝胆、心小肠、脾胃等',
          '气血津液的生成与运行',
          '脏腑失调的病理表现',
        ],
        order: 2,
      },
      {
        id: 'rj-nj-03',
        title: '诊断方法',
        subtitle: '望闻问切四诊',
        description: '中医四诊——望（观察）、闻（听闻）、问（询问）、切（脉诊）的具体方法。',
        keyPoints: [
          '望诊：面色、舌象、形体、神态',
          '闻诊：声音、气味的辨别',
          '问诊：寒热、汗、疼痛、二便等',
          '切诊：脉象的基本分类与诊断意义',
        ],
        order: 3,
      },
    ],
  },
  {
    id: 'rj-bencao',
    category: 'renji',
    name: '神农本草经',
    nameEn: 'Shen Nong Ben Cao Jing',
    subtitle: '人纪第三课 · 药物学根基',
    description: '《神农本草经》是中药学的鼻祖，倪师按上中下三品分类讲解365味药物的性味归经与临床运用。',
    details: [
      '《神农本草经》将药物分为上品（养命）、中品（养性）、下品（治病）三类。',
      '倪师的讲解重点在于每味药的核心功效和临床实际运用，而非死记硬背。',
      '课程特别强调「药有真假」——如何辨别药材的真伪和质量。',
      '倪师认为掌握本草经是开方用药的根基，没有这个基础，伤寒论和金匮的方剂就无法灵活运用。',
    ],
    lessons: '46集（每集约1小时）',
    references: [
      '《神农本草经》',
      '倪海厦《人纪·神农本草经》讲义',
    ],
    keywords: ['神农本草经', '中药', '本草', '上品', '中品', '下品', '性味归经', '药性'],
    icon: '⚘',
    status: 'active',
    order: 3,
    slug: 'bencao',
    chapters: [
      {
        id: 'rj-bc-01',
        title: '上品药物',
        subtitle: '养命延年 · 无毒',
        description: '上品120味，主养命以应天，无毒，多服久服不伤人。',
        keyPoints: [
          '人参：大补元气，生津止渴',
          '黄芪：补气固表，利水消肿',
          '甘草：调和诸药，补中益气',
          '上品药可作为日常调养之用',
        ],
        order: 1,
      },
      {
        id: 'rj-bc-02',
        title: '中品药物',
        subtitle: '养性补虚 · 有毒无毒',
        description: '中品120味，主养性以应人，无毒有毒，斟酌其宜。',
        keyPoints: [
          '当归：补血活血，调经止痛',
          '黄芩：清热燥湿，泻火解毒',
          '白术：健脾益气，燥湿利水',
          '中品药需要根据病情斟酌使用',
        ],
        order: 2,
      },
      {
        id: 'rj-bc-03',
        title: '下品药物',
        subtitle: '治病祛邪 · 有毒',
        description: '下品125味，主治病以应地，多毒不可久服。',
        keyPoints: [
          '附子：回阳救逆，大热',
          '大黄：泻下攻积，清热泻火',
          '巴豆：峻下冷积，有大毒',
          '下品药针对性强，需谨慎使用',
        ],
        order: 3,
      },
    ],
  },
  {
    id: 'rj-shanghan',
    category: 'renji',
    name: '伤寒论',
    nameEn: 'Shang Han Lun',
    subtitle: '人纪第四课 · 辨证论治典范',
    description: '张仲景《伤寒论》是中医辨证论治的典范之作，倪师逐条讲解六经辨证体系与经方运用。',
    details: [
      '《伤寒论》以六经（太阳、阳明、少阳、太阴、少阴、厥阴）辨证为纲，系统阐述外感病的诊治。',
      '倪师的讲解注重临床实用性，每一条文都结合实际病例说明。',
      '经方（张仲景的方剂）是中医临床的核心武器，倪师强调「经方一剂知，二剂已」的神效。',
      '倪师认为伤寒论不仅治外感，更是治疗一切疾病的方法论基础。',
    ],
    lessons: '伤寒论原版DVD（每集约2小时）',
    references: [
      '《伤寒论》（张仲景）',
      '倪海厦《人纪·伤寒论》讲义',
    ],
    keywords: ['伤寒论', '张仲景', '六经辨证', '经方', '太阳病', '阳明病', '少阳病', '桂枝汤', '麻黄汤'],
    icon: '⚕',
    status: 'active',
    order: 4,
    slug: 'shanghan',
    chapters: [
      {
        id: 'rj-sh-01',
        title: '六经辨证总论',
        subtitle: '太阳阳明少阳太阴少阴厥阴',
        description: '六经辨证是伤寒论的核心框架，将一切外感病按六经归类，指导治疗方向。',
        keyPoints: [
          '太阳病：恶寒发热，头痛项强——表证',
          '阳明病：壮热汗出，大渴大烦——里实热证',
          '少阳病：往来寒热，胸胁苦满——半表半里',
          '太阴病：腹满而吐，食不下——里虚寒证',
          '少阴病：脉微细，但欲寐——阳虚寒化或阴虚热化',
          '厥阴病：消渴，气上撞心——寒热错杂',
        ],
        order: 1,
      },
      {
        id: 'rj-sh-02',
        title: '核心经方',
        subtitle: '桂枝汤、麻黄汤等经典方剂',
        description: '伤寒论中最重要的方剂，每一首方都有明确的适应症和使用条件。',
        keyPoints: [
          '桂枝汤：调和营卫，太阳中风第一方',
          '麻黄汤：发汗解表，太阳伤寒第一方',
          '小柴胡汤：和解少阳，柴胡证的主方',
          '白虎汤：清阳明里热',
          '四逆汤：回阳救逆，少阴寒化的主方',
        ],
        order: 2,
      },
      {
        id: 'rj-sh-03',
        title: '方证辨析',
        subtitle: '同病异治与异病同治',
        description: '通过伤寒论的条文学习辨证论治的精髓——同一疾病可用不同方剂，不同疾病可用同一方剂。',
        keyPoints: [
          '辨证而非辨病：看的是证型而非病名',
          '方证对应：每个方剂有其特定的适应症候群',
          '经方加减：根据兼证灵活加减',
          '传经与变证的判断',
        ],
        order: 3,
      },
    ],
  },
  {
    id: 'rj-jingui',
    category: 'renji',
    name: '金匮要略',
    nameEn: 'Jin Gui Yao Lue',
    subtitle: '人纪第五课 · 杂病诊治大成',
    description: '张仲景《金匮要略》是中医杂病治疗的最高经典，倪师讲解各种内科杂病的辨证论治方法。',
    details: [
      '《金匮要略》是《伤寒杂病论》的杂病部分，与《伤寒论》互为补充。',
      '伤寒论主治外感，金匮主治内伤杂病——两者合起来就是张仲景的完整临床体系。',
      '倪师的讲解涵盖痰饮、水气、黄疸、妇人病等各类杂病的诊治。',
      '金匮是人纪最后一门课，需要前四门课的知识基础才能理解运用。',
    ],
    lessons: '20集（每集约1小时）',
    references: [
      '《金匮要略》（张仲景）',
      '倪海厦《人纪·金匮要略》讲义',
    ],
    keywords: ['金匮要略', '张仲景', '杂病', '痰饮', '水气', '黄疸', '妇人病', '经方'],
    icon: '⚗',
    status: 'active',
    order: 5,
    slug: 'jingui',
    chapters: [
      {
        id: 'rj-jg-01',
        title: '杂病总论',
        subtitle: '病因病机与治则',
        description: '杂病的发病原因、病理机制与治疗原则的总论。',
        keyPoints: [
          '内伤杂病与外感病的区别',
          '五脏风寒的辨证方法',
          '虚实寒热的鉴别要点',
          '治未病的预防思想',
        ],
        order: 1,
      },
      {
        id: 'rj-jg-02',
        title: '痰饮水气',
        subtitle: '痰饮四类与水肿治法',
        description: '痰饮、悬饮、溢饮、支饮四种痰饮病的辨证论治，以及水气病的治疗。',
        keyPoints: [
          '痰饮四类的鉴别',
          '水气病（风水、皮水、正水、石水）',
          '苓桂术甘汤：痰饮病的基础方',
          '五苓散：水气病的常用方',
        ],
        order: 2,
      },
      {
        id: 'rj-jg-03',
        title: '妇人病与杂病各论',
        subtitle: '妇科与各科杂病',
        description: '妇人妊娠病、产后病、杂病以及其他各科杂病的辨证论治。',
        keyPoints: [
          '妇人妊娠病的治疗原则',
          '产后三大病（痉、郁冒、大便难）',
          '黄疸的辨证分型与治疗',
          '胸痹（胸痛）的治疗方剂',
        ],
        order: 3,
      },
    ],
  },
];

// ─── 215条针灸经验穴位（倪师临床精华） ────────────────────
export const ACU_EXPERIENCES: AcuExperience[] = [
  // 01 心·心血管系统
  { id: 1, condition: '冠心病', acupoints: '关元、巨阙、少府、涌泉、公孙', category: '心血管' },
  { id: 2, condition: '心脏肥大', acupoints: '巨阙、少府、神门、劳宫、关元、公孙、内关、天突', category: '心血管' },
  { id: 3, condition: '心绞痛', acupoints: '厉兑、人中、十宣（放血）、涌泉、百会（放血）', category: '心血管' },
  { id: 4, condition: '真心痛', acupoints: '巨阙、关元、天突、厉兑', category: '心血管' },
  { id: 5, condition: '心律不齐', acupoints: '关元、太渊', category: '心血管' },
  { id: 6, condition: '心悸', acupoints: '神门、少府、关元', category: '心血管' },
  { id: 7, condition: '心脏痛', acupoints: '公孙、内关、巨阙、关元、天突、厉兑', category: '心血管' },
  // 02 肝胆系统
  { id: 8, condition: '肝病', acupoints: '肝关、行间', category: '肝胆' },
  { id: 9, condition: '肝炎', acupoints: '行间', category: '肝胆' },
  { id: 10, condition: '肝硬化', acupoints: '肝俞、行间', category: '肝胆' },
  { id: 11, condition: '肝硬化腹水', acupoints: '水分、水道、肝关', category: '肝胆' },
  { id: 12, condition: '黄疸', acupoints: '脊中、行间', category: '肝胆' },
  { id: 13, condition: '胆结石', acupoints: '肝俞、胆俞、阳陵泉正下约一寸处（胆石点）', category: '肝胆' },
  // 03 脾胃消化系统
  { id: 14, condition: '胃病胃痛', acupoints: '中脘（梅花灸）、关元、天枢、公孙、内关', category: '脾胃' },
  { id: 15, condition: '胃癌', acupoints: '膺窗、鱼际、足三里、天溪、痞根、地五会', category: '脾胃' },
  { id: 16, condition: '腹痛', acupoints: '三阴交、公孙、关元、中极、肠关', category: '脾胃' },
  { id: 17, condition: '腹胀', acupoints: '水分（灸）、公孙、消积', category: '脾胃' },
  { id: 18, condition: '胃酸过多', acupoints: '公孙、内关', category: '脾胃' },
  { id: 19, condition: '消化不良', acupoints: '公孙、内关、腹通谷', category: '脾胃' },
  { id: 20, condition: '呕吐', acupoints: '公孙、内关、中脘、胃俞', category: '脾胃' },
  { id: 21, condition: '恶心反胃', acupoints: '中脘、公孙', category: '脾胃' },
  { id: 22, condition: '腹泻', acupoints: '天枢、大横、肠关、四满', category: '脾胃' },
  { id: 23, condition: '便秘', acupoints: '支沟、照海', category: '脾胃' },
  { id: 24, condition: '痔疮', acupoints: '长强、孔最、秩边、承山', category: '脾胃' },
  { id: 25, condition: '便血', acupoints: '下髎', category: '脾胃' },
  { id: 26, condition: '结直肠癌', acupoints: '痞根、消积', category: '脾胃' },
  { id: 27, condition: '结核性肠炎', acupoints: '神阙（灸）、温溜', category: '脾胃' },
  { id: 28, condition: '阑尾炎', acupoints: '阑尾、天枢、中脘、关元、足三里、肘尖（灸）', category: '脾胃' },
  { id: 29, condition: '疝气', acupoints: '隐白、肝俞、大敦（对侧）、行间', category: '脾胃' },
  { id: 30, condition: '水肿', acupoints: '水分、三阴交、地机、阴陵泉、水道', category: '脾胃' },
  // 04 肺·呼吸系统
  { id: 31, condition: '肺癌', acupoints: '中府、云门、孔最、公孙、内关', category: '肺系' },
  { id: 32, condition: '气喘', acupoints: '膻中、中府、云门、孔最、公孙、内关', category: '肺系' },
  { id: 33, condition: '咳嗽', acupoints: '太渊、灵墟、俞府、彧中', category: '肺系' },
  { id: 34, condition: '多痰', acupoints: '丰隆', category: '肺系' },
  { id: 35, condition: '鼻子不通', acupoints: '迎香、合谷（对侧）、通天', category: '肺系' },
  { id: 36, condition: '喉哑失声', acupoints: '哑门（禁灸）', category: '肺系' },
  { id: 37, condition: '胸中瘀血', acupoints: '巨骨', category: '肺系' },
  { id: 38, condition: '肺结核', acupoints: '肺俞、胆俞、膈俞', category: '肺系' },
  { id: 39, condition: '肺积水', acupoints: '膈俞、膻中、鸠尾、阳谷、后溪、照海、水分、水道、大包', category: '肺系' },
  // 05 肾·泌尿系统
  { id: 40, condition: '肾虚', acupoints: '肾俞、京门、命门', category: '肾系' },
  { id: 41, condition: '遗精', acupoints: '三阴交（灸）、横骨', category: '肾系' },
  { id: 42, condition: '前列腺肥大', acupoints: '阴陵泉、关元、足三里', category: '肾系' },
  { id: 43, condition: '阳强阳挺', acupoints: '蠡沟、曲泉', category: '肾系' },
  { id: 44, condition: '阴茎痛小腹痛', acupoints: '列缺、三阴交、次髎、大敦、行间', category: '肾系' },
  { id: 45, condition: '阴缩', acupoints: '大赫、大敦、行间', category: '肾系' },
  { id: 46, condition: '生殖器病', acupoints: '大敦', category: '肾系' },
  { id: 47, condition: '阴痛', acupoints: '少府', category: '肾系' },
  { id: 48, condition: '小便不利', acupoints: '中极、关元、三阴交、大钟、阴包', category: '肾系' },
  { id: 49, condition: '小便痛', acupoints: '大敦、阴包', category: '肾系' },
  { id: 50, condition: '尿频', acupoints: '中极、关元、阴陵泉', category: '肾系' },
  { id: 51, condition: '尿失禁', acupoints: '阴陵泉', category: '肾系' },
  { id: 52, condition: '肾结石', acupoints: '肾俞、京门、命门、交信和太溪之间（肾石点）', category: '肾系' },
  // 06 妇科·儿科
  { id: 53, condition: '痛经', acupoints: '关元（灸）、中极（灸）、三阴交、血海', category: '妇科' },
  { id: 54, condition: '月经过少', acupoints: '血海（血海下一寸针）', category: '妇科' },
  { id: 55, condition: '月经过多', acupoints: '隐白、行间', category: '妇科' },
  { id: 56, condition: '崩漏', acupoints: '隐白、交信、行间', category: '妇科' },
  { id: 57, condition: '赤白带下', acupoints: '隐白、次髎、阴谷、大赫、白环俞', category: '妇科' },
  { id: 58, condition: '子宫肌瘤', acupoints: '下巨虚、地机、三阴交', category: '妇科' },
  { id: 59, condition: '子宫下垂', acupoints: '交信、大敦', category: '妇科' },
  { id: 60, condition: '阴道痉挛', acupoints: '大敦', category: '妇科' },
  { id: 61, condition: '阴道痒', acupoints: '曲泉', category: '妇科' },
  { id: 62, condition: '阴唇痒', acupoints: '阴交（灸）', category: '妇科' },
  { id: 63, condition: '不孕症', acupoints: '关元（灸）、气冲、中极、上髎（灸）', category: '妇科' },
  { id: 64, condition: '孕吐', acupoints: '中脘、公孙', category: '妇科' },
  { id: 65, condition: '胎位不正', acupoints: '至阴', category: '妇科' },
  { id: 66, condition: '难产', acupoints: '支沟', category: '妇科' },
  { id: 67, condition: '胎盘不下', acupoints: '昆仑、太溪', category: '妇科' },
  { id: 68, condition: '产后恶露', acupoints: '中都', category: '妇科' },
  { id: 69, condition: '退乳断奶', acupoints: '陷谷、上巨虚', category: '妇科' },
  { id: 70, condition: '乳房疼痛', acupoints: '神封、内庭', category: '妇科' },
  { id: 71, condition: '乳房肿胀', acupoints: '上巨虚、内庭', category: '妇科' },
  { id: 72, condition: '乳炎乳瘫', acupoints: '内庭', category: '妇科' },
  { id: 73, condition: '乳腺小叶增生', acupoints: '上巨虚、天溪、地五会', category: '妇科' },
  { id: 74, condition: '乳房纤维瘤', acupoints: '天溪、地五会', category: '妇科' },
  { id: 75, condition: '乳腺癌', acupoints: '肩井、膺窗、鱼际、足三里、天溪、痞根、地五会', category: '妇科' },
  // 07 神志·神经
  { id: 76, condition: '脑血栓', acupoints: '百会', category: '神志', note: '无昏迷时用' },
  { id: 77, condition: '中风', acupoints: '百会、风府', category: '神志' },
  { id: 78, condition: '中风中经络', acupoints: '风市、阳陵泉、阴陵泉、悬钟、三阴交', category: '神志' },
  { id: 79, condition: '半身不遂', acupoints: '环跳、风市、阴市、悬钟', category: '神志' },
  { id: 80, condition: '周期性瘫痪', acupoints: '风市、阴市', category: '神志' },
  { id: 81, condition: '失眠', acupoints: '三毛（灸）、神门', category: '神志' },
  { id: 82, condition: '癫痫', acupoints: '申脉（灸）、照海（灸）、鸠尾、百会、人中、涌泉', category: '神志' },
  { id: 83, condition: '脑震荡', acupoints: '然谷（放血）', category: '神志' },
  { id: 84, condition: '红斑狼疮', acupoints: '心俞、肺俞、肝俞', category: '神志' },
  { id: 85, condition: '痴呆', acupoints: '悬钟、痞根', category: '神志' },
  { id: 86, condition: '肋间神经痛', acupoints: '肝关', category: '神志' },
  { id: 87, condition: '癫狂', acupoints: '筋缩', category: '神志' },
  { id: 88, condition: '脑瘤', acupoints: '百会、涌泉', category: '神志' },
  // 08 伤痛外科
  { id: 89, condition: '颈椎病', acupoints: '昆仑、后溪、申脉', category: '伤科' },
  { id: 90, condition: '头项强重', acupoints: '后溪、申脉、大杼、昆仑', category: '伤科' },
  { id: 91, condition: '落枕', acupoints: '手三里', category: '伤科' },
  { id: 92, condition: '五十肩', acupoints: '偏历、条口、承山、曲池、二间', category: '伤科' },
  { id: 93, condition: '肩膀酸痛', acupoints: '肩中俞、肩外俞、曲池、肩井、足三里', category: '伤科' },
  { id: 94, condition: '肩拉伤', acupoints: '肩井、足三里', category: '伤科' },
  { id: 95, condition: '网球肘', acupoints: '曲池（拔罐放血）、手三里', category: '伤科' },
  { id: 96, condition: '手指痛', acupoints: '合谷透劳宫、三间透后溪', category: '伤科' },
  { id: 97, condition: '腰痛', acupoints: '委中、肾俞、大肠俞', category: '伤科' },
  { id: 98, condition: '坐骨神经痛', acupoints: '环跳、阳陵泉、委中、悬钟', category: '伤科' },
  { id: 99, condition: '膝痛', acupoints: '风市、阴市、膝阳关透曲泉', category: '伤科' },
  { id: 100, condition: '脚扭伤', acupoints: '商丘透丘墟', category: '伤科', note: '一针见效' },
  // 09 五官科
  { id: 101, condition: '头痛（前额）', acupoints: '合谷、阳白', category: '五官' },
  { id: 102, condition: '头痛（偏头）', acupoints: '太阳透率谷、丝竹空（放血）', category: '五官' },
  { id: 103, condition: '头痛（后脑）', acupoints: '后溪、申脉、昆仑', category: '五官' },
  { id: 104, condition: '头痛（头顶）', acupoints: '陷谷透涌泉', category: '五官' },
  { id: 105, condition: '面瘫', acupoints: '阳白透鱼腰、地仓透颊车、丝竹空透太阳', category: '五官' },
  { id: 106, condition: '白内障', acupoints: '阳白透鱼腰、睛明、球后、承泣、养老', category: '五官' },
  { id: 107, condition: '近视眼', acupoints: '阳白透鱼腰、翳风、丘墟', category: '五官' },
  { id: 108, condition: '色盲', acupoints: '臂臑透肩髃、复溜、睛明、光明', category: '五官' },
  { id: 109, condition: '耳鸣', acupoints: '耳门、听宫、听会、肾俞、翳风', category: '五官' },
  { id: 110, condition: '牙痛', acupoints: '合谷、颊车、下关', category: '五官' },
  // 10 其他
  { id: 111, condition: '戒烟', acupoints: '列缺透阳溪、筑宾、合谷、肺俞', category: '其他' },
  { id: 112, condition: '盗汗', acupoints: '神门透阴郄、内关', category: '其他' },
  { id: 113, condition: '狐臭', acupoints: '肩髃透极泉', category: '其他' },
  { id: 114, condition: '疟疾', acupoints: '外关透内关、大椎、命门', category: '其他' },
  { id: 115, condition: '中暑昏厥', acupoints: '水沟透龈交、十宣放血', category: '其他' },
  { id: 116, condition: '皮肤痒', acupoints: '三间透合谷、筑宾、至阴、曲池、血海', category: '其他' },
  { id: 117, condition: '脚跟痛', acupoints: '大陵透足根点、承山、仆参、水泉', category: '其他' },
  { id: 118, condition: '静脉曲张', acupoints: '三阴交、足三里、承山、委中', category: '其他' },
  { id: 119, condition: '发烧', acupoints: '大椎、曲池、合谷、外关', category: '其他' },
  { id: 120, condition: '感冒', acupoints: '风池、风府、大椎、合谷', category: '其他' },
];

// ─── 31条透针透穴法 ────────────────────────────────────────
export const TRANS_NEEDLING: TransNeedling[] = [
  { id: 1, combo: '中府透云门', indication: '咳嗽、气喘、哮喘、肺癌', supporting: '孔最、公孙、内关', source: '倪海厦' },
  { id: 2, combo: '阳陵泉透阴陵泉', indication: '中风、中经络、雷诺氏病', supporting: '内关、水沟、三阴交、极泉', source: '孙培荣/周左宇/倪海厦' },
  { id: 3, combo: '悬钟透三阴交', indication: '中风、肩膀痛、上肢神经痛', supporting: '阳陵泉', source: '孙培荣/周左宇/倪海厦' },
  { id: 4, combo: '曲池透少海', indication: '半身不遂、偏瘫', supporting: '先针健侧泻法再针患侧补法', source: '孙培荣' },
  { id: 5, combo: '水沟透龈交', indication: '晕倒、晕厥', supporting: '涌泉、关元、丰隆', source: '周左宇' },
  { id: 6, combo: '四神聪透百会', indication: '痴呆', supporting: '印堂、神庭、上星、风池', source: '孙培荣' },
  { id: 7, combo: '神庭透上星', indication: '脑瘫、智力低下', supporting: '四神聪、百会、印堂、风池', source: '孙培荣' },
  { id: 8, combo: '液门透中渚', indication: '臂丛神经痛', supporting: '三间', source: '孙培荣' },
  { id: 9, combo: '合谷透劳宫', indication: '雷诺氏病', supporting: '内关、太渊、阴陵泉、阳陵泉', source: '孙培荣' },
  { id: 10, combo: '条口透承山', indication: '肩膀诸痛', supporting: '阳陵泉、曲垣、肩井', source: '孙培荣/周左宇/倪海厦' },
  { id: 11, combo: '悬钟透三阴交+天髎透曲垣', indication: '肩胛痛、膏肓痛', supporting: '郄门、曲池、肩井、足三里', source: '孙培荣/周左宇/倪海厦' },
  { id: 12, combo: '养老透间使', indication: '臂痛、肘痛', supporting: '液门、中渚、曲池', source: '孙培荣/周左宇/倪海厦' },
  { id: 13, combo: '陷谷透涌泉', indication: '手痛诸证', supporting: '小海、外关、合谷', source: '倪海厦' },
  { id: 14, combo: '三间透劳宫', indication: '手痛、手胀、手木、手麻', supporting: '曲池、肩井、外关', source: '倪海厦' },
  { id: 15, combo: '合谷透劳宫/三间透后溪', indication: '手指痛', source: '倪海厦' },
  { id: 16, combo: '膝阳关透曲泉', indication: '膝盖诸疾', supporting: '风市、阴市', source: '孙培荣' },
  { id: 17, combo: '商丘透丘墟', indication: '脚扭伤', source: '倪海厦' },
  { id: 18, combo: '大陵透足根点', indication: '脚跟痛', supporting: '承山、仆参、水泉', source: '孙培荣' },
  { id: 19, combo: '膝阳关透曲泉', indication: '曲池少海部位不适', source: '孙培荣/周左宇' },
  { id: 20, combo: '三间透合谷', indication: '皮肤痒', supporting: '筑宾、至阴、屋翳、内庭、曲池、血海', source: '孙培荣' },
  { id: 21, combo: '阳白透鱼腰+丝竹空透太阳+地仓透颊车', indication: '面瘫、口眼歪斜', supporting: '先健后患', source: '孙培荣/周左宇/倪海厦' },
  { id: 22, combo: '阳白透鱼腰', indication: '白内障、近视眼', supporting: '睛明、球后、承泣、养老、翳风、丘墟', source: '倪海厦' },
  { id: 23, combo: '太阳透率谷', indication: '偏头痛', supporting: '对侧合谷麻醉、丝竹空放血、然谷', source: '孙培荣' },
  { id: 24, combo: '陷谷透涌泉', indication: '百会痛（头顶痛）', source: '孙培荣' },
  { id: 25, combo: '臂臑透肩髃', indication: '色盲、视神经萎缩', supporting: '复溜、睛明、丝竹空、光明', source: '孙培荣/周左宇' },
  { id: 26, combo: '攒竹透鱼腰/丝竹空透鱼腰', indication: '眼睛不闭、眉棱骨痛', supporting: '阳陵泉', source: '孙培荣' },
  { id: 27, combo: '液门透中渚', indication: '耳鸣', supporting: '翳风、耳门、听会、肾俞', source: '周左宇' },
  { id: 28, combo: '列缺透阳溪', indication: '戒烟', supporting: '筑宾、合谷、肺俞', source: '孙培荣' },
  { id: 29, combo: '神门透阴郄', indication: '盗汗、手汗', supporting: '内关、手五里、间使', source: '周左宇' },
  { id: 30, combo: '外关透内关', indication: '疟疾', supporting: '大椎、命门、委中', source: '孙培荣' },
  { id: 31, combo: '肩髃透极泉', indication: '狐臭', source: '倪海厦' },
];

// ─── 汉唐100方完整列表 ────────────────────────────────────
export const HANTANG_FORMULAS: HantangFormula[] = [
  { id: 1, name: '白带丸', indication: '女性赤白带过多', theory: '乳汁下行变化为月经，肝经主疏泄' },
  { id: 2, name: '退乳丸', indication: '退乳汁，预防乳癌', theory: '乳汁与月经同源' },
  { id: 3, name: '补髓丹', indication: '记忆力减退、老年痴呆', theory: '脑为髓海，髓源于肾精', ingredients: '杜仲、补骨脂、鹿茸、没药、核桃肉' },
  { id: 4, name: '皮肤过敏丸', indication: '食物过敏引起皮肤红疹瘙痒', theory: '脾胃功能不足致过敏' },
  { id: 5, name: '通乳丸', indication: '乳汁不足、乳房硬块', theory: '加强心脏热能使乳汁下行', ingredients: '附子、生姜、柴胡、黄芩、桂枝、半夏' },
  { id: 6, name: '手抖心颤方', indication: '手抖、心颤、心脏病早期', theory: '心火不足致心脏压缩力不衡', ingredients: '半夏、桂枝、黄连、白术' },
  { id: 7, name: '胃痈方', indication: '胃痈及胃出血', theory: '血不归经则出血' },
  { id: 8, name: '子宫症痼方', indication: '子宫肌瘤、子宫肿瘤', theory: '加强心脏热能使瘀血排出', ingredients: '桂枝、茯苓、丹皮、白芍' },
  { id: 9, name: '血箭痔丸', indication: '大便前出血如箭射', theory: '小肠湿热下注', ingredients: '百草霜、栀子花、榴花、地榆' },
  { id: 10, name: '大禹丸', indication: '肝癌末期腹腔积水', theory: '大禹治水排腹水', ingredients: '十枣汤加减' },
  { id: 11, name: '代抵当丸', indication: '子宫干血、膀胱蓄血', theory: '破血活血排除瘀血', ingredients: '水蛭、虻虫、桃仁、大黄' },
  { id: 12, name: '脱肛丸', indication: '脱肛、肛门下坠', theory: '中气下陷致直肠脱垂' },
  { id: 13, name: '淋痛方', indication: '小便刺痛、淋症', theory: '相火外泄、热结下焦' },
  { id: 14, name: '胆石方', indication: '胆结石、胆囊息肉', theory: '肝气郁滞、胆汁排泄不利' },
  { id: 15, name: '真寒假热方', indication: '血癌、白血病', theory: '阳气过亢、阴液不足' },
  { id: 16, name: '干痒癣方', indication: '皮肤干燥、牛皮癣', theory: '肺主皮毛，强化肺津液输布' },
  { id: 17, name: '湿疹脓疮方', indication: '皮肤湿疹、黄水疮', theory: '脾运化不足致脾湿肠燥' },
  { id: 18, name: '蛇方', indication: '带状疱疹', theory: '经络不通、火气上逆' },
  { id: 19, name: '焦虑方', indication: '气血两虚型焦虑抑郁', theory: '肺主气心主血不足' },
  { id: 20, name: '四肢无力方', indication: '下肢无力、肌肉萎缩', theory: '脾运化功能不足' },
  { id: 21, name: '补阳还五丸', indication: '中风后遗症、瘫痪', theory: '气虚血瘀阻滞脑部' },
  { id: 22, name: '奔豚汤', indication: '奔豚气、腹部动悸', theory: '浊气上冲、气机错乱' },
  { id: 23, name: '降压方', indication: '高血压、中风预防', theory: '肝升肺敛失衡', ingredients: '桔梗、五味子、桃仁、丹皮' },
  { id: 24, name: '消渴方', indication: '糖尿病、消渴症', theory: '脾运化不足致血糖失常', ingredients: '山茱萸、生地、石膏' },
  { id: 25, name: '疏通经络剂', indication: '三叉神经痛', theory: '经络不通、火气上逆' },
  { id: 26, name: '石淋方', indication: '肾结石、尿路结石', theory: '肝郁相火煎熬水液成石' },
  { id: 27, name: '痛风丸', indication: '痛风、关节红肿剧痛', theory: '郁则生风、毒气积聚关节' },
  { id: 28, name: '风湿丸', indication: '风湿性关节炎', theory: '风寒湿三邪痰饮停留关节' },
  { id: 29, name: '消痔丸', indication: '外痔疮、肛门痛痒', theory: '升气血解毒' },
  { id: 30, name: '坐骨神经痛方', indication: '坐骨神经痛、腰痛', theory: '经络堵塞、椎间盘突出压迫' },
  { id: 31, name: '三酸甘油脂方', indication: '三酸甘油脂过高', theory: '中焦湿热过盛' },
  { id: 32, name: '乌金丸', indication: '心痛澈背、背痛澈心', theory: '心脏病前兆' },
  { id: 33, name: '湿热便秘方', indication: '中焦湿热兼便秘', theory: '湿热壅结大肠' },
  { id: 34, name: '补天丸', indication: '掉头发、耳鸣', theory: '肾精不足' },
  { id: 35, name: '紫金丹', indication: '胸腔内伤、上身瘀血', theory: '活血化瘀' },
  { id: 36, name: '天青丸', indication: '妇女痛经、下身瘀血', theory: '增加小肠热量促进静脉回流' },
  { id: 37, name: '天威丸', indication: '男性精子不足', theory: '补肾壮精' },
  { id: 38, name: '玉华丸', indication: '女性滋补', theory: '滋补阴液' },
  { id: 39, name: '鼻渊丸', indication: '鼻塞不通、流清涕', theory: '温肺通窍' },
  { id: 40, name: '乌梅丸', indication: '各种寄生虫、蛔虫', theory: '驱虫安蛔' },
  { id: 41, name: '中安丸', indication: '失眠', theory: '交通心肾' },
  { id: 42, name: '控涎丹', indication: '痰阻塞胸肺、癫痫', theory: '攻逐痰饮' },
  { id: 43, name: '麻子仁丸', indication: '大便如羊屎小颗粒', theory: '润肠通便' },
  { id: 44, name: '皂荚丸', indication: '清除肺中吸烟浊痰', theory: '涤痰清肺' },
  { id: 45, name: '己椒苈黄丸', indication: '右腹胀、肠间水气', theory: '分消湿热水饮' },
  { id: 46, name: '六味地黄丸', indication: '滋阴补肾通用', theory: '三补三泻' },
  { id: 47, name: '重阳丸', indication: '男子精中带血', theory: '固肾清相火' },
  { id: 48, name: '金匮肾气丸', indication: '手脚冰冷、强化肾脏', theory: '补肾助阳' },
  { id: 49, name: '起阳丸', indication: '振奋阳气、增强性功能', theory: '生精壮阳' },
  { id: 50, name: '牙痛止痛剂', indication: '牙痛', theory: '清热止痛' },
  { id: 52, name: '赤丸', indication: '心脏肥大、动脉剥离', theory: '心阳不足致心脏代偿肥大', ingredients: '半夏、枳实、炙甘草' },
  { id: 53, name: '风引汤', indication: '风痱（中风后四肢无力）', theory: '排出骨节深层风寒湿' },
  { id: 54, name: '喉蛾方', indication: '扁桃腺发炎', theory: '相火不收藏冲击咽喉' },
  { id: 55, name: '紫云膏', indication: '皮肤生坚结（外用）', theory: '活血化瘀外用' },
  { id: 56, name: '汉唐红', indication: '外用伤口特效药', theory: '活血生肌' },
  { id: 57, name: '佛州黑', indication: '外用烫伤特效药', theory: '清热生肌' },
  { id: 58, name: '白内障药水', indication: '白内障（外用）', theory: '外用通窍明目' },
  { id: 59, name: '喷鼻药粉', indication: '鼻炎过敏、昏迷急救', theory: '开脑窍刺激鼻窦' },
  { id: 60, name: '强力天青丸', indication: '双足静脉曲张', theory: '增强小肠热量促进静脉回流' },
  { id: 61, name: '明目地黄丸', indication: '眼睛保养、视力不足', theory: '肝开窍在眼、补肝明目' },
  { id: 62, name: '沉香桂附丸', indication: '少腹痛、下利、双足冷', theory: '沉香引火归元温肾气' },
  { id: 63, name: '骨损方', indication: '骨质疏松症', theory: '肾主骨、补肾强骨' },
  { id: 64, name: '更年期方', indication: '经停后身热盗汗', theory: '子宫萎缩热能回逆三焦' },
  { id: 65, name: '膀胱结石方', indication: '膀胱结石、尿道炎', theory: '清利湿热' },
  { id: 66, name: '前列腺方', indication: '前列腺肥大、膀胱无力', theory: '增强膀胱气化功能' },
  { id: 67, name: '失心丸', indication: '癫痫发狂', theory: '阴乔阳乔失衡、清肺痰' },
  { id: 68, name: '护肝丸', indication: '乙肝及各类肝病', theory: '见肝之病知肝传脾当先实脾' },
  { id: 69, name: '肾积水方', indication: '肾积水、下肢水肿', theory: '恢复肾脏排尿功能' },
  { id: 70, name: '定心丸', indication: '心肾不交、焦虑忧郁', theory: '心火下行肾水上升' },
  { id: 71, name: '清郁开结丸', indication: '强烈沮丧、忧郁感', theory: '肝郁脾结开郁升肝木' },
  { id: 72, name: '浮萍方', indication: '小儿风痒、皮肤病', theory: '浮萍辛凉利湿止痒' },
  { id: 73, name: '透脓方', indication: '四肢末梢坏疽', theory: '增加小肠热力驱邪生肌' },
  { id: 74, name: '搜风解毒汤', indication: '性病泡疹淋病梅毒', theory: '清除病毒由小便排出' },
  { id: 75, name: '枕中丹', indication: '令人聪明', theory: '补脑益智' },
  { id: 76, name: '避孕丸', indication: '避孕', theory: '中药避孕' },
  { id: 77, name: '心绞痛方', indication: '心脏动脉阻塞', theory: '清肝毒排血管瘀物' },
  { id: 78, name: '健胃散', indication: '各种胃病', theory: '温降调理胃气' },
  { id: 79, name: '青春痘方', indication: '青春痘', theory: '相火旺盛排毒表现' },
  { id: 80, name: '减肥丸', indication: '过胖症', theory: '心脏是唯一控制体重的脏器' },
  { id: 81, name: '鼻过敏头痛方', indication: '鼻过敏合并头痛', theory: '鼻窍堵塞阻断气血', ingredients: '白附子、僵蚕' },
  { id: 82, name: '下焦寒实方', indication: '前列腺癌', theory: '导引心热下行至小肠', ingredients: '炮附、细辛、五味子、丹皮、木通、桂枝' },
  { id: 83, name: '皮肤诸病粉', indication: '皮肤生疮化脓（外用）', theory: '去湿化脓生新皮', ingredients: '密陀僧、雄黄' },
  { id: 84, name: '肝结石方', indication: '胆切除后肝结石', theory: '失去胆吸力致胆汁积滞', ingredients: '柴胡、枳实、黄芩、郁金、海金沙' },
  { id: 85, name: '青春痘外用粉', indication: '青春痘（外用）', theory: '滋润清炎' },
  { id: 86, name: '脚气方', indication: '脚气病香港脚（外用）', theory: '杀菌除湿' },
  { id: 87, name: '心脏肥大方', indication: '心脏肥大症', theory: '心阳不足代偿性变化' },
  { id: 88, name: '磁珠丸', indication: '白内障、青光眼', theory: '磁石收纳肾气交通心肾', ingredients: '磁石、决明子、神曲' },
  { id: 89, name: '健筋骨丸', indication: '骨折、肌肉萎缩、坐骨神经痛', theory: '肝主筋肾主骨乙癸同源' },
  { id: 90, name: '消瘤丸', indication: '甲状腺肿瘤（大脖子）', theory: '阳气行则阴不积' },
  { id: 92, name: '增高丸', indication: '身材矮小', theory: '补肾精同时收敛阴成形' },
  { id: 93, name: '小儿过动症方', indication: '多动症ADHD', theory: '心火上炎肾水不济', ingredients: '木通、附子' },
  { id: 95, name: '拖里化毒饮', indication: '淋巴脓块、乳房脓块', theory: '里拖毒外拔毒相结合' },
  { id: 96, name: '乳癌外用粉', indication: '乳癌脓块（外用）', theory: '外用拔毒' },
  { id: 97, name: '何首乌丸', indication: '白发、延年益寿', theory: '何首乌补肝血养精气' },
  { id: 98, name: '五石乌头丸', indication: '严重癌症、严重风湿', theory: '金石丹药攻力猛', ingredients: '钟乳、硫磺、矾石、紫石英、赤石脂、乌头、附子等32味' },
  { id: 99, name: '斑龙丸', indication: '脑受损、肾阴阳两虚', theory: '鹿角鹿茸补厥下海底阴' },
  { id: 100, name: '历节丸', indication: '类风湿性关节炎', theory: '源自金匮乌头汤症', ingredients: '生乌头' },
];

// ─── 核心经方精选（伤寒论+金匮要略） ──────────────────────
export const CLASSIC_FORMULAS: ClassicFormula[] = [
  { id: 'cf-01', name: '桂枝汤', source: '伤寒论', composition: '桂枝10g、白芍10g、生姜二片、炙甘草10g、红枣十枚', indication: '太阳中风，调和营卫', niUsage: '太阳中风第一方，脉浮缓有汗恶风' },
  { id: 'cf-02', name: '麻黄汤', source: '伤寒论', composition: '麻黄9g、桂枝6g、杏仁9g、炙甘草3g', indication: '太阳伤寒，发汗解表', niUsage: '脉浮紧无汗恶寒身疼' },
  { id: 'cf-03', name: '小柴胡汤', source: '伤寒论', composition: '柴胡24g、黄芩9g、半夏9g、生姜9g、人参9g、甘草6g、大枣12枚', indication: '和解少阳', niUsage: '往来寒热胸胁苦满' },
  { id: 'cf-04', name: '白虎汤', source: '伤寒论', composition: '石膏50g、知母18g、甘草6g、粳米一合', indication: '清阳明里热', niUsage: '壮热汗出大渴大烦' },
  { id: 'cf-05', name: '四逆汤', source: '伤寒论', composition: '附子一枚、干姜9g、炙甘草6g', indication: '回阳救逆', niUsage: '少阴寒化主方，四肢厥冷脉微细' },
  { id: 'cf-06', name: '小青龙汤', source: '伤寒论', composition: '麻黄12g、芍药9g、干姜9g、半夏9g、桂枝6g、炙甘草6g、细辛3g、五味子3g', indication: '表寒里寒伴水饮', niUsage: '外寒内饮咳喘痰多清稀' },
  { id: 'cf-07', name: '大青龙汤', source: '伤寒论', composition: '麻黄12g、桂枝6g、杏仁6g、石膏如鸡蛋大、甘草6g、生姜9g、大枣12枚', indication: '表实里热', niUsage: '恶寒无汗烦躁' },
  { id: 'cf-08', name: '葛根汤', source: '伤寒论', composition: '葛根12g、麻黄9g、桂枝6g、芍药6g、甘草6g、生姜9g、大枣12枚', indication: '太阳阳明合病项背强', niUsage: '项背强几几、下利' },
  { id: 'cf-09', name: '真武汤', source: '伤寒论', composition: '附子一枚、茯苓9g、白术6g、芍药9g、生姜9g', indication: '阳虚水泛', niUsage: '心下悸、头眩、身瞤动' },
  { id: 'cf-10', name: '理中汤', source: '伤寒论', composition: '人参9g、白术9g、干姜9g、甘草9g', indication: '中焦虚寒', niUsage: '腹痛吐利、四肢不温' },
  { id: 'cf-11', name: '苓桂术甘汤', source: '金匮', composition: '茯苓12g、桂枝9g、白术6g、甘草6g', indication: '痰饮病基础方', niUsage: '心下逆满气上冲胸头眩' },
  { id: 'cf-12', name: '五苓散', source: '伤寒论', composition: '猪苓9g、泽泻15g、茯苓9g、白术9g、桂枝6g', indication: '水气病', niUsage: '小便不利、渴欲饮水' },
  { id: 'cf-13', name: '桂枝加葛根汤', source: '伤寒论', composition: '桂枝汤加葛根12g', indication: '太阳中风项背强', niUsage: '项背强几几有汗' },
  { id: 'cf-14', name: '桂枝加厚朴杏仁汤', source: '伤寒论', composition: '桂枝汤加厚朴、杏仁', indication: '表证兼咳喘', niUsage: '太阳中风兼喘' },
  { id: 'cf-15', name: '麻杏甘石汤', source: '伤寒论', composition: '麻黄6g、杏仁9g、甘草6g、石膏24g', indication: '发汗后咳喘热盛', niUsage: '汗出而喘' },
  { id: 'cf-16', name: '大承气汤', source: '伤寒论', composition: '大黄12g、芒硝9g、厚朴15g、枳实12g', indication: '阳明腑实证', niUsage: '痞满燥实四证俱全' },
  { id: 'cf-17', name: '小承气汤', source: '伤寒论', composition: '大黄12g、厚朴6g、枳实9g', indication: '阳明腑实轻证', niUsage: '痞满不燥实' },
  { id: 'cf-18', name: '当归四逆汤', source: '伤寒论', composition: '当归9g、桂枝9g、芍药9g、细辛3g、通草6g、甘草6g、大枣25枚', indication: '血虚寒凝手足厥冷', niUsage: '手足厥寒、脉细欲绝' },
  { id: 'cf-19', name: '乌梅丸', source: '伤寒论', composition: '乌梅30枚、细辛6g、干姜10g、黄连9g、当归4g、附子6g、蜀椒4g、桂枝6g、人参6g、黄柏6g', indication: '厥阴病寒热错杂蛔厥', niUsage: '消渴气上撞心饥而不欲食' },
  { id: 'cf-20', name: '炙甘草汤', source: '伤寒论', composition: '炙甘草12g、生姜9g、人参6g、生地黄48g、桂枝9g、阿胶6g、麦冬12g、麻仁12g、大枣30枚', indication: '心动悸脉结代', niUsage: '气血不足心律不齐' },
  { id: 'cf-21', name: '肾气丸', source: '金匮', composition: '干地黄24g、山药12g、山茱萸12g、泽泻9g、茯苓9g、丹皮9g、桂枝3g、炮附子3g', indication: '肾阳不足', niUsage: '腰痛脚软小便不利' },
  { id: 'cf-22', name: '桂枝茯苓丸', source: '金匮', composition: '桂枝、茯苓、丹皮、桃仁、芍药各等分', indication: '瘀血阻滞胞宫', niUsage: '妊娠下血不止、子宫肌瘤' },
  { id: 'cf-23', name: '温经汤', source: '金匮', composition: '吴茱萸9g、当归6g、芍药6g、川芎6g、人参6g、桂枝6g、阿胶6g、丹皮6g、生姜6g、甘草6g、半夏6g、麦冬9g', indication: '冲任虚寒瘀血阻滞', niUsage: '妇人少腹寒、久不受胎' },
  { id: 'cf-24', name: '防己黄芪汤', source: '金匮', composition: '防己12g、黄芪15g、白术9g、甘草6g、生姜4片、大枣1枚', indication: '风水、风湿表虚', niUsage: '汗出恶风身重小便不利' },
  { id: 'cf-25', name: '小建中汤', source: '伤寒论', composition: '桂枝9g、芍药18g、甘草6g、生姜9g、大枣12枚、饴糖30g', indication: '中焦虚寒腹痛', niUsage: '腹中急痛、虚劳' },
];

// ─── 统计 ────────────────────────────────────────────────
export const RENJI_STATS = {
  totalModules: RENJI_MODULES.length,
  totalChapters: RENJI_MODULES.reduce((sum, m) => sum + m.chapters.length, 0),
  totalLessons: '150+集',
  completionYear: '2004-2005',
  learningOrder: ['针灸大成', '黄帝内经', '神农本草经', '伤寒论', '金匮要略'],
  acuExperienceCount: 215,
  transNeedlingCount: 31,
  hantangFormulaCount: 100,
  classicFormulaCount: 259,
};
