/**
 * 天纪 — 倪海厦天文术数体系数据库
 *
 * 「上知天文」—— 天之纪，是术数研究的体系化成果。
 * 1994年录制，共24集视频（每集2小时，共48小时）。
 * 讲义分为《天机道》《人间道》《地脉道》《64卦易图》四册。
 *
 * 核心学派：
 *   紫微斗数 → 三合派
 *   风水     → 九星派（杨救贫流派）
 *   易经     → 象数派
 *   推命     → 河洛数理派
 */

import type { NiModule, Hexagram, FengShuiEntry, TianjiEpisode } from './types';

// ─── 天纪模块 ────────────────────────────────────────────
export const TIANJI_MODULES: NiModule[] = [
  {
    id: 'tj-ziwei',
    category: 'tianji',
    name: '紫微斗数',
    nameEn: 'Zi Wei Dou Shu',
    subtitle: '三合派 · 倪师正宗体系',
    description: '以紫微星为主轴，十四主星配十二宫位，结合四化星推演人生格局。倪师主张「大道至简」，不用飞星派复杂化法，以三合派为正宗。',
    details: [
      '紫微斗数是倪师天纪课程的核心命学工具，属三合派体系。倪师明言：「飞星（四化）飞来飞去太复杂，不搞这个，毕竟大道至简。」',
      '课程以十二张案例讲义为教材，紫微星在十二个位置各一张，从子宫到亥宫绕一圈，覆盖所有主星排列。',
      '倪师强调命宫为本、三方为用——命宫主星决定基本格局与天生性格，三方（财帛、官禄、迁移）决定用武之地。',
      '四化星（化禄、化权、化科、化忌）的运用是核心技法，配合大限流年推演人生关键节点。',
    ],
    school: '三合派',
    lessons: '天纪视频前半部分（约24小时）',
    references: [
      '《紫微斗数全集》',
      '《紫微斗数全书》',
      '《骨髓赋》',
      '倪海厦《天纪》讲义（天机道篇）',
    ],
    keywords: ['紫微斗数', '三合派', '十四主星', '十二宫位', '四化星', '大限', '流年', '命宫', '三方四正', '格局'],
    icon: '◉',
    status: 'active',
    order: 1,
    slug: 'ziwei',
    chapters: [
      {
        id: 'tj-zw-01',
        title: '紫微斗数基础',
        subtitle: '安星法与排盘原理',
        description: '从年支排盘入手，了解紫微斗数的基本安星规则、十二宫位的含义与相互关系。',
        keyPoints: [
          '以年支排盘，非子平法的年柱排列',
          '十二宫位：命宫、兄弟、夫妻、子女、财帛、疾厄、迁移、交友、官禄、田宅、福德、父母',
          '命宫为一切分析的起点',
          '身宫可看影响最重的宫位',
        ],
        quotes: ['身宫在财帛宫的女孩子，一般来说就是职业妇女'],
        order: 1,
      },
      {
        id: 'tj-zw-02',
        title: '十四主星详解',
        subtitle: '星性与庙旺利陷',
        description: '深入讲解紫微、天机、太阳、武曲、天同、廉贞、天府、太阴、贪狼、巨门、天相、天梁、七杀、破军十四颗主星的性质。',
        keyPoints: [
          '每颗主星有独特的性格特质与命理意涵',
          '亮度系统（庙/旺/得/利/平/不/陷）影响星力发挥',
          '杀破狼三星一定同在三方，构成变动格局',
          '紫微星为帝座，天府为财库',
        ],
        quotes: ['最怕的是七杀临身，七杀临身的人一辈子多败少成'],
        order: 2,
      },
      {
        id: 'tj-zw-03',
        title: '四化星运用',
        subtitle: '化禄化权化科化忌',
        description: '四化星是紫微斗数的灵魂技法，每年天干对应四颗星化入不同宫位，推动命运变化。',
        keyPoints: [
          '化禄星主财，性守——代表财运和享受',
          '化权星性刚，代表官印——代表权力和掌控',
          '化科星主科名，名气很大——代表名声和贵人',
          '化忌星主劫杀——代表阻碍和困难',
          '大限四化与流年四化叠加判断',
        ],
        order: 3,
      },
      {
        id: 'tj-zw-04',
        title: '格局与断命',
        subtitle: '经典格局与实战案例',
        description: '从杀破狼、火贪格等经典格局入手，结合倪师十二张案例讲义实战断命。',
        keyPoints: [
          '官禄宫最喜欢权星入进来',
          '杀破狼格局代表变动与开创',
          '火贪格主暴发',
          '命相同参可提高准确率',
          '结合面相（五形论）辅助判断',
        ],
        order: 4,
      },
    ],
  },
  {
    id: 'tj-yijing',
    category: 'tianji',
    name: '易经六十四卦',
    nameEn: 'Yi Jing 64 Hexagrams',
    subtitle: '象数派 · 断易天机',
    description: '倪师以《断易天机》为底本，自创图示法讲解六十四卦，前一小时讲命学，后一小时讲易经，相辅相成。',
    details: [
      '易经部分以象数派为主，倪师自行演变的易图是独特教学工具，极大简化了学习难度。',
      '64卦图解底本来自《断易天机》，倪师重新排列、注解，形成独有的图示教学法。',
      '课程不仅教卦理，更注重实际占卜应用：如何起卦、解卦、断事。',
      '倪师强调易经不仅是占卜工具，更是决策智慧——「不但看到时机，还能马上做决策」。',
    ],
    school: '象数派',
    lessons: '天纪视频后半部分（约24小时）',
    references: [
      '《断易天机》',
      '《周易》',
      '倪海厦《人间道·64卦易图》',
    ],
    keywords: ['易经', '六十四卦', '八卦', '象数派', '占卜', '断易天机', '图示法', '六爻'],
    icon: '☰',
    status: 'active',
    order: 2,
    slug: 'yijing',
    chapters: [
      {
        id: 'tj-yj-01',
        title: '易经基础与八卦',
        subtitle: '阴阳与先后天八卦',
        description: '从太极生两仪、两仪生四象、四象生八卦入手，建立易经的基础知识体系。',
        keyPoints: [
          '乾（天）、兑（泽）、离（火）、震（雷）、巽（风）、坎（水）、艮（山）、坤（地）',
          '先天八卦与后天八卦的区别',
          '八卦的象征意义与自然对应',
          '六爻的由来与结构',
        ],
        order: 1,
      },
      {
        id: 'tj-yj-02',
        title: '六十四卦详解',
        subtitle: '图示法与卦辞解读',
        description: '逐卦讲解六十四卦的卦象、卦辞、爻辞要义，配合倪师独创图示法。',
        keyPoints: [
          '每卦由上下两个三爻卦叠合而成',
          '卦辞揭示整体趋势，爻辞指示具体位置',
          '变卦（动爻）是断事的关键',
          '倪师图解简化了传统解卦的复杂性',
        ],
        order: 2,
      },
      {
        id: 'tj-yj-03',
        title: '占卜实战',
        subtitle: '起卦与断事方法',
        description: '从起卦方法到断事技巧，覆盖完整的占卜实战流程。',
        keyPoints: [
          '多种起卦法：揲蓍法、金钱卦、梅花易数等',
          '用神取用与六亲关系',
          '六神（青龙、朱雀、勾陈、腾蛇、白虎、玄武）占断',
          '时间、方位、事态的综合判断',
        ],
        order: 3,
      },
    ],
  },
  {
    id: 'tj-kanyu',
    category: 'tianji',
    name: '堪舆学',
    nameEn: 'Kan Yu Xue',
    subtitle: '九星派 · 杨救贫流派',
    description: '涵盖阳宅风水与阴宅选择，以九星派（杨救贫流派）为正宗，讲解三吉六秀、八煞黄泉等核心风水理论。',
    details: [
      '堪舆学是天纪课程「下知地理」的核心板块，属于《地脉道》讲义内容。',
      '倪师采用杨救贫九星派体系，强调峦头（山形水势）与理气（方位吉凶）并重。',
      '阳宅部分讲解居住环境对人生的影响，包括房屋朝向、内部布局、周围环境等。',
      '阴宅部分讲解墓地选择与立向，强调「八煞黄泉」是绝对禁忌的方位。',
      '倪师认为「人事的努力加上地理上的调整，一定能大于先天的命运」，即2/3大于1/3的核心理念。',
    ],
    school: '九星派（杨救贫流派）',
    lessons: '天纪视频第18-21集',
    references: [
      '倪海厦《地脉道》讲义',
      '杨救贫风水典籍',
    ],
    keywords: ['堪舆', '风水', '阳宅', '阴宅', '九星派', '杨救贫', '八煞黄泉', '三吉六秀', '峦头', '理气'],
    icon: '⊞',
    status: 'active',
    order: 3,
    slug: 'kanyu',
    chapters: [
      {
        id: 'tj-ky-01',
        title: '阳宅风水',
        subtitle: '居住环境与人生运势',
        description: '讲解住宅选择与布局的风水原理，包括朝向、格局、周围环境对居住者的影响。',
        keyPoints: [
          '三吉方向（生气、延年、天医）与六秀方向的概念',
          '房屋坐向与居住者八字的配合',
          '室内布局：厨房、卧室、书房的方位选择',
          '居住位置、睡眠方向对人生轨迹的影响',
        ],
        order: 1,
      },
      {
        id: 'tj-ky-02',
        title: '阴宅风水',
        subtitle: '墓地选择与立向',
        description: '讲解墓地选址的峦头理论与立向禁忌，强调八煞黄泉等绝对禁忌。',
        keyPoints: [
          '八煞黄泉：坟墓和阳宅立向的绝对禁忌',
          '天星四贵的概念与应用',
          '龙穴砂水的基本判断',
          '城局与九星的配合',
        ],
        order: 2,
      },
      {
        id: 'tj-ky-03',
        title: '风水与命运',
        subtitle: '地理调整改善运势',
        description: '倪师关于风水与命运关系的核心理论——人事努力+地理调整>先天命运。',
        keyPoints: [
          '2/3大于1/3理论：人事努力+地理=2/3，先天命运=1/3',
          '好的风水地方要有鱼虾龟（生气充沛的标志）',
          '来龙、朝山、砂势的综合判断',
          '结合紫微斗数的田宅宫来看风水需求',
        ],
        order: 3,
      },
    ],
  },
  {
    id: 'tj-tuiming',
    category: 'tianji',
    name: '推命学',
    nameEn: 'Tui Ming Xue',
    subtitle: '河洛数理派 · 子平法',
    description: '以子平法排列的易经推命术，结合河洛数理派理论，是紫微斗数之外的另一套命学工具。',
    details: [
      '推命学在天纪中作为紫微斗数的补充命学工具出现。',
      '倪师介绍了两种命学体系：一是子平法排列的八字推命术，二是紫微斗数用年支排盘的方式。',
      '河洛数理派注重数字与五行的对应关系，从数理角度分析命运轨迹。',
      '倪师建议学生应同时掌握多种命学工具，以便交叉验证、提高准确度。',
    ],
    school: '河洛数理派',
    lessons: '天纪课程穿插讲解',
    references: [
      '《子平真诠》',
      '《河洛数理》',
    ],
    keywords: ['推命', '八字', '子平法', '河洛数理', '四柱', '五行', '天干地支'],
    icon: '⊡',
    status: 'preview',
    order: 4,
    slug: 'tuiming',
    chapters: [
      {
        id: 'tj-tm-01',
        title: '四柱八字基础',
        subtitle: '天干地支与五行',
        description: '子平法的基础知识，包括天干地支的五行属性、十神关系、大运流年的排列。',
        keyPoints: [
          '十天干与十二地支的五行属性',
          '年柱、月柱、日柱、时柱的排列',
          '十神体系与六亲关系',
          '大运排列与流年推演',
        ],
        order: 1,
      },
    ],
  },
  {
    id: 'tj-mianxiang',
    category: 'tianji',
    name: '面相学',
    nameEn: 'Mian Xiang Xue',
    subtitle: '五形论 · 命相同参',
    description: '面相学是天纪课程中辅助命理判断的重要工具，倪师强调「命相同参会提高准确率」。',
    details: [
      '面相学以「五形论」为核心——木、火、土、金、水五种面相类型。',
      '倪师强调五形的「纯正性」决定贵贱：越纯正的面相类型越贵。',
      '特殊贵相的识别：「南人北相、北人南相」是贵相的重要标志。',
      '面相不是孤立判断，必须结合紫微斗数的命盘分析，做到「命相同参」。',
    ],
    school: '五形面相',
    lessons: '天纪课程穿插讲解',
    references: [
      '《麻衣相法》',
      '《神相全编》',
    ],
    keywords: ['面相', '五形论', '木火土金水', '命相同参', '南人北相', '气色'],
    icon: '⊙',
    status: 'preview',
    order: 5,
    slug: 'mianxiang',
    chapters: [
      {
        id: 'tj-mx-01',
        title: '五形论基础',
        subtitle: '木火土金水面相分类',
        description: '五种基本面相类型的特征识别与贵贱判断。',
        keyPoints: [
          '木形人：身材高瘦，面长色青',
          '火形人：面尖上阔，色红气急',
          '土形人：面圆肉厚，色黄声重',
          '金形人：面方骨正，色白声清',
          '水形人：面圆肉浮，色黑性柔',
        ],
        order: 1,
      },
    ],
  },
  {
    id: 'tj-cezi',
    category: 'tianji',
    name: '测字术',
    nameEn: 'Ce Zi Shu',
    subtitle: '拆字法 · 会意法',
    description: '测字是中国传统占卜术之一，通过分析文字的笔画、结构、含义来推断吉凶。',
    details: [
      '测字术在天纪课程中作为辅助占卜手段出现。',
      '主要方法包括拆字法（分解字形）和会意法（联想字义）。',
      '倪师认为测字的准确性取决于测者的悟性和经验积累。',
    ],
    school: '传统测字',
    lessons: '天纪课程穿插讲解',
    references: [
      '《拆字辞典》',
    ],
    keywords: ['测字', '拆字法', '会意法', '占卜'],
    icon: '⊚',
    status: 'coming',
    order: 6,
    slug: 'cezi',
    chapters: [
      {
        id: 'tj-cz-01',
        title: '测字基础',
        subtitle: '拆字与会意',
        description: '测字术的基本方法与实战技巧。',
        keyPoints: [
          '拆字法：将文字拆解为偏旁部首分别解读',
          '会意法：根据文字含义联想推断',
          '时间与环境因素的结合',
        ],
        order: 1,
      },
    ],
  },
];

// ─── 易经六十四卦数据库 ──────────────────────────────────
export const HEXAGRAMS: Hexagram[] = [
  { number: 1, name: '乾', composition: '乾为天', upper: '乾', lower: '乾', meaning: '元亨利贞，天行健，君子以自强不息', niInterpretation: '纯阳之卦，刚健中正，至大至刚', divination: '大吉大利，但需注意亢龙有悔' },
  { number: 2, name: '坤', composition: '坤为地', upper: '坤', lower: '坤', meaning: '元亨，利牝马之贞，地势坤，君子以厚德载物', niInterpretation: '纯阴之卦，柔顺承载', divination: '宜顺从，不宜主动' },
  { number: 3, name: '屯', composition: '水雷屯', upper: '坎', lower: '震', meaning: '元亨利贞，勿用有攸往', niInterpretation: '万物初生之象，创业维艰', divination: '初创时期，宜守不宜进' },
  { number: 4, name: '蒙', composition: '山水蒙', upper: '艮', lower: '坎', meaning: '亨，匪我求童蒙，童蒙求我', niInterpretation: '启蒙教育之卦，需有耐心', divination: '求学问道有利，需虚心受教' },
  { number: 5, name: '需', composition: '水天需', upper: '坎', lower: '乾', meaning: '有孚，光亨贞吉，利涉大川', niInterpretation: '等待时机之卦，需要耐心', divination: '宜等待时机成熟再行动' },
  { number: 6, name: '讼', composition: '天水讼', upper: '乾', lower: '坎', meaning: '有孚窒惕，中吉终凶', niInterpretation: '争讼之卦，不宜争斗', divination: '争讼不利，宜和解退让' },
  { number: 7, name: '师', composition: '地水师', upper: '坤', lower: '坎', meaning: '贞丈人吉，无咎', niInterpretation: '统兵之卦，需正义之师', divination: '行事需有正当名分' },
  { number: 8, name: '比', composition: '水地比', upper: '坎', lower: '坤', meaning: '吉，原筮元永贞，无咎', niInterpretation: '亲附比辅之卦，团结互助', divination: '宜寻求合作与结盟' },
  { number: 9, name: '小畜', composition: '风天小畜', upper: '巽', lower: '乾', meaning: '亨，密云不雨，自我西郊', niInterpretation: '小有积蓄之卦，力量不足以大成', divination: '小事可成，大事尚需等待' },
  { number: 10, name: '履', composition: '天泽履', upper: '乾', lower: '兑', meaning: '履虎尾，不咥人，亨', niInterpretation: '行事谨慎之卦，如履虎尾', divination: '小心谨慎可化险为夷' },
  { number: 11, name: '泰', composition: '地天泰', upper: '坤', lower: '乾', meaning: '小往大来，吉亨', niInterpretation: '天地交泰，通达之象', divination: '万事亨通，大吉' },
  { number: 12, name: '否', composition: '天地否', upper: '乾', lower: '坤', meaning: '否之匪人，不利君子贞', niInterpretation: '天地不交，闭塞之象', divination: '诸事不顺，宜守待时' },
  { number: 13, name: '同人', composition: '天火同人', upper: '乾', lower: '离', meaning: '同人于野，亨，利涉大川', niInterpretation: '志同道合之卦', divination: '合作共事有利' },
  { number: 14, name: '大有', composition: '火天大有', upper: '离', lower: '乾', meaning: '元亨', niInterpretation: '大丰收之卦，光明正大', divination: '事业丰盛，大有所获' },
  { number: 15, name: '谦', composition: '地山谦', upper: '坤', lower: '艮', meaning: '亨，君子有终', niInterpretation: '谦逊之卦，唯一六爻皆吉之卦', divination: '谦虚谨慎，诸事吉利' },
  { number: 16, name: '豫', composition: '雷地豫', upper: '震', lower: '坤', meaning: '利建侯行师', niInterpretation: '安乐和豫之卦，但不可过度', divination: '可有所作为，但勿过于安逸' },
  { number: 17, name: '随', composition: '泽雷随', upper: '兑', lower: '震', meaning: '元亨利贞，无咎', niInterpretation: '随顺之卦，择善而从', divination: '随机应变，顺势而行' },
  { number: 18, name: '蛊', composition: '山风蛊', upper: '艮', lower: '巽', meaning: '元亨，利涉大川', niInterpretation: '整治积弊之卦，拨乱反正', divination: '需要整顿改革' },
  { number: 19, name: '临', composition: '地泽临', upper: '坤', lower: '兑', meaning: '元亨利贞，至于八月有凶', niInterpretation: '亲临监督之卦，居高临下', divination: '可有所作为，但注意时效' },
  { number: 20, name: '观', composition: '风地观', upper: '巽', lower: '坤', meaning: '盥而不荐，有孚颙若', niInterpretation: '观察审视之卦，以下观上', divination: '宜观察形势，不宜冒进' },
  { number: 21, name: '噬嗑', composition: '火雷噬嗑', upper: '离', lower: '震', meaning: '亨，利用狱', niInterpretation: '刑罚决断之卦，去除障碍', divination: '果断处理障碍，排除困难' },
  { number: 22, name: '贲', composition: '山火贲', upper: '艮', lower: '离', meaning: '亨，小利有攸往', niInterpretation: '文饰之卦，外在修饰', divination: '注重外表形式，小事可成' },
  { number: 23, name: '剥', composition: '山地剥', upper: '艮', lower: '坤', meaning: '不利有攸往', niInterpretation: '剥落衰败之卦', divination: '不宜行动，宜守静待变' },
  { number: 24, name: '复', composition: '地雷复', upper: '坤', lower: '震', meaning: '亨，出入无疾，朋来无咎', niInterpretation: '一阳来复之卦，否极泰来', divination: '转机出现，渐入佳境' },
  { number: 25, name: '无妄', composition: '天雷无妄', upper: '乾', lower: '震', meaning: '元亨利贞', niInterpretation: '无妄之灾亦需坦然面对', divination: '正道而行可吉，妄动则凶' },
  { number: 26, name: '大畜', composition: '山天大畜', upper: '艮', lower: '乾', meaning: '利贞，不家食吉，利涉大川', niInterpretation: '大有积蓄之卦，厚积薄发', divination: '积累实力，蓄势待发' },
  { number: 27, name: '颐', composition: '山雷颐', upper: '艮', lower: '震', meaning: '贞吉，观颐，自求口实', niInterpretation: '养生颐养之卦', divination: '注意饮食养生，自力更生' },
  { number: 28, name: '大过', composition: '泽风大过', upper: '兑', lower: '巽', meaning: '栋桡，利有攸往，亨', niInterpretation: '阳气过盛之卦，过犹不及', divination: '事情过度，需要调整' },
  { number: 29, name: '坎', composition: '坎为水', upper: '坎', lower: '坎', meaning: '习坎，有孚，维心亨', niInterpretation: '重重险难之卦，但心诚可亨', divination: '困难重重，但坚守信念可过关' },
  { number: 30, name: '离', composition: '离为火', upper: '离', lower: '离', meaning: '利贞，亨，畜牝牛吉', niInterpretation: '光明附丽之卦，文明之象', divination: '宜守正道，光明正大' },
  { number: 31, name: '咸', composition: '泽山咸', upper: '兑', lower: '艮', meaning: '亨利贞，取女吉', niInterpretation: '感应之卦，男女相感', divination: '感情婚姻大吉' },
  { number: 32, name: '恒', composition: '雷风恒', upper: '震', lower: '巽', meaning: '亨，无咎利贞，利有攸往', niInterpretation: '恒久不变之卦，持之以恒', divination: '坚持不懈可成功' },
  { number: 33, name: '遁', composition: '天山遁', upper: '乾', lower: '艮', meaning: '亨，小利贞', niInterpretation: '退隐之卦，适时退避', divination: '宜退不宜进，暂避锋芒' },
  { number: 34, name: '大壮', composition: '雷天大壮', upper: '震', lower: '乾', meaning: '利贞', niInterpretation: '刚强壮盛之卦，但壮不可妄动', divination: '力量充沛，但需守正' },
  { number: 35, name: '晋', composition: '火地晋', upper: '离', lower: '坤', meaning: '康侯用锡马蕃庶', niInterpretation: '日出地上之卦，步步高升', divination: '事业晋升，前途光明' },
  { number: 36, name: '明夷', composition: '地火明夷', upper: '坤', lower: '离', meaning: '利艰贞', niInterpretation: '光明损伤之卦，韬光养晦', divination: '宜隐藏光芒，低调行事' },
  { number: 37, name: '家人', composition: '风火家人', upper: '巽', lower: '离', meaning: '利女贞', niInterpretation: '家庭和睦之卦', divination: '家庭事务吉利' },
  { number: 38, name: '睽', composition: '火泽睽', upper: '离', lower: '兑', meaning: '小事吉', niInterpretation: '背离分歧之卦，求同存异', divination: '小事可成，大事不宜' },
  { number: 39, name: '蹇', composition: '水山蹇', upper: '坎', lower: '艮', meaning: '利西南，不利东北', niInterpretation: '行路艰难之卦', divination: '前路困难，宜结伴同行' },
  { number: 40, name: '解', composition: '雷水解', upper: '震', lower: '坎', meaning: '利西南，无所往', niInterpretation: '解除困难之卦，雨过天晴', divination: '困难解除，宜速行事' },
  { number: 41, name: '损', composition: '山泽损', upper: '艮', lower: '兑', meaning: '有孚，元吉，无咎', niInterpretation: '损下益上之卦，适当牺牲', divination: '有所舍才有所得' },
  { number: 42, name: '益', composition: '风雷益', upper: '巽', lower: '震', meaning: '利有攸往，利涉大川', niInterpretation: '损上益下之卦，有利可图', divination: '事业有益，宜大胆行动' },
  { number: 43, name: '夬', composition: '泽天夬', upper: '兑', lower: '乾', meaning: '扬于王庭', niInterpretation: '决断之卦，以阳决阴', divination: '需果断处理，不可犹豫' },
  { number: 44, name: '姤', composition: '天风姤', upper: '乾', lower: '巽', meaning: '女壮，勿用取女', niInterpretation: '相遇之卦，一阴初生', divination: '偶然相遇，不宜深交' },
  { number: 45, name: '萃', composition: '泽地萃', upper: '兑', lower: '坤', meaning: '亨，王假有庙', niInterpretation: '聚集之卦，众志成城', divination: '聚集力量，团结协作' },
  { number: 46, name: '升', composition: '地风升', upper: '坤', lower: '巽', meaning: '元亨，用见大人', niInterpretation: '上升之卦，步步高升', divination: '事业上升，宜见贵人' },
  { number: 47, name: '困', composition: '泽水困', upper: '兑', lower: '坎', meaning: '亨贞，大人吉，无咎', niInterpretation: '困顿之卦，但大人可吉', divination: '身处困境，守正可渡' },
  { number: 48, name: '井', composition: '水风井', upper: '坎', lower: '巽', meaning: '改邑不改井', niInterpretation: '水井之卦，不变中的恒常', divination: '固守根本，不可轻易改变' },
  { number: 49, name: '革', composition: '泽火革', upper: '兑', lower: '离', meaning: '己日乃孚', niInterpretation: '变革之卦，革故鼎新', divination: '时机成熟可变革' },
  { number: 50, name: '鼎', composition: '火风鼎', upper: '离', lower: '巽', meaning: '元吉，亨', niInterpretation: '鼎新之卦，建立新制', divination: '事业更新，大吉' },
  { number: 51, name: '震', composition: '震为雷', upper: '震', lower: '震', meaning: '亨，震来虩虩', niInterpretation: '震动之卦，初惊后安', divination: '先有惊扰，后可安定' },
  { number: 52, name: '艮', composition: '艮为山', upper: '艮', lower: '艮', meaning: '艮其背，不获其身', niInterpretation: '止静之卦，适可而止', divination: '宜停止观望，不宜冒进' },
  { number: 53, name: '渐', composition: '风山渐', upper: '巽', lower: '艮', meaning: '女归吉，利贞', niInterpretation: '循序渐进之卦', divination: '宜循序渐进，不可操之过急' },
  { number: 54, name: '归妹', composition: '雷泽归妹', upper: '震', lower: '兑', meaning: '征凶，无攸利', niInterpretation: '少女出嫁之卦，位置不正', divination: '感情事宜需谨慎' },
  { number: 55, name: '丰', composition: '雷火丰', upper: '震', lower: '离', meaning: '亨，王假之', niInterpretation: '丰盛之卦，日中则昃', divination: '盛极必衰，宜居安思危' },
  { number: 56, name: '旅', composition: '火山旅', upper: '离', lower: '艮', meaning: '小亨，旅贞吉', niInterpretation: '旅行在外之卦', divination: '旅行出行小吉，需谨慎' },
  { number: 57, name: '巽', composition: '巽为风', upper: '巽', lower: '巽', meaning: '小亨，利有攸往', niInterpretation: '顺从之卦，柔顺渗透', divination: '宜顺势而为，不宜强行' },
  { number: 58, name: '兑', composition: '兑为泽', upper: '兑', lower: '兑', meaning: '亨利贞', niInterpretation: '喜悦之卦，和悦相处', divination: '和乐融融，社交有利' },
  { number: 59, name: '涣', composition: '风水涣', upper: '巽', lower: '坎', meaning: '亨，王假有庙', niInterpretation: '涣散之卦，化解分散', divination: '团队涣散，需凝聚人心' },
  { number: 60, name: '节', composition: '水泽节', upper: '坎', lower: '兑', meaning: '亨，苦节不可贞', niInterpretation: '节制之卦，适度为宜', divination: '凡事需节制，过犹不及' },
  { number: 61, name: '中孚', composition: '风泽中孚', upper: '巽', lower: '兑', meaning: '豚鱼吉，利涉大川', niInterpretation: '诚信之卦，至诚感通', divination: '诚信待人，可成大事' },
  { number: 62, name: '小过', composition: '雷山小过', upper: '震', lower: '艮', meaning: '亨利贞，可小事不可大事', niInterpretation: '小有过越之卦', divination: '小事可为，大事不宜' },
  { number: 63, name: '既济', composition: '水火既济', upper: '坎', lower: '离', meaning: '亨小，利贞，初吉终乱', niInterpretation: '事已成就之卦，但需谨防衰败', divination: '事情已成，但需注意善后' },
  { number: 64, name: '未济', composition: '火水未济', upper: '离', lower: '坎', meaning: '亨，小狐汔济，濡其尾', niInterpretation: '尚未完成之卦，事在人为', divination: '事未完成，需继续努力' },
];

// ─── 堪舆学条目 ──────────────────────────────────────────
export const FENGSHUI_ENTRIES: FengShuiEntry[] = [
  {
    id: 'fs-bashayq',
    title: '八煞黄泉',
    category: 'theory',
    description: '立向的绝对禁忌，坟墓和阳宅都不可犯。八煞黄泉是风水学中最严重的忌讳之一。',
    keyPoints: ['坟墓和阳宅立向使用', '绝对不能立的向', '犯之主大凶'],
  },
  {
    id: 'fs-sanjilx',
    title: '三吉六秀',
    category: 'yangzhai',
    description: '阳宅风水中的吉利方位。三吉方向（生气、延年、天医）代表最佳的方位选择。',
    keyPoints: ['三吉：生气、延年、天医', '六秀方向有好的砂势则吉', '有山势、来龙、朝山为佳'],
  },
  {
    id: 'fs-tianxsg',
    title: '天星四贵',
    category: 'yinzhai',
    description: '阴宅选址的高级技法，用于判断墓地周围的贵气方位。',
    keyPoints: ['天星方位判断贵气', '与龙穴砂水配合使用', '九星派核心理论之一'],
  },
  {
    id: 'fs-yangzhai',
    title: '阳宅布局',
    category: 'yangzhai',
    description: '居住环境的风水布局原则，包括房屋坐向、室内格局、周围环境的综合考量。',
    keyPoints: ['房屋坐向需配合居住者', '厨房方位影响家人健康', '卧室位置影响夫妻感情', '居住位置与睡眠方向影响运势'],
  },
  {
    id: 'fs-longxueshashui',
    title: '龙穴砂水',
    category: 'yinzhai',
    description: '风水四大要素——龙脉走势、穴位选择、砂的环抱、水的流向，构成完整的风水格局。',
    keyPoints: ['龙：山脉走势与来龙', '穴：藏风聚气的最佳位置', '砂：穴位周围的山势环抱', '水：水流走向与聚散'],
  },
  {
    id: 'fs-chengjujiuxing',
    title: '城局与九星',
    category: 'theory',
    description: '杨救贫九星派的核心理论，通过九星的排列组合判断风水格局的吉凶。',
    keyPoints: ['九星：贪巨禄文廉武破左右', '城局形势的整体判断', '与天星四贵配合使用'],
  },
];

// ─── 天纪24集课程结构（每集2小时：前半段命学/后半段易经） ──
export const TIANJI_EPISODES: TianjiEpisode[] = [
  { dvd: 1, firstHalf: '天纪开篇·天纪与真理', secondHalf: '易经三义·先后天八卦', highlights: ['如何分辨君子与小人', '天地人三才论', '紫微斗数为何优于子平法', '文字只是船真理才是彼岸'] },
  { dvd: 2, firstHalf: '紫微斗数·十二宫位详解', secondHalf: '八卦地理配置·爻变与时机', highlights: ['命宫为本三方为用', '夫妻宫兼看福德宫', '面相五形论', '名位相等原则', '卜筮有时机不疑何卜'] },
  { dvd: 3, firstHalf: '紫微斗数·星辰介绍(上)', secondHalf: '乾坤屯蒙需讼', highlights: ['紫微星帝座特质', '天府财库星', '太阳星庙旺利陷', '天机善星智慧'] },
  { dvd: 4, firstHalf: '紫微斗数·星辰介绍(下)', secondHalf: '师比小畜履泰否', highlights: ['杀破狼三星一定同在三方', '武曲财星', '贪狼桃花星', '廉贞囚星', '巨门暗星'] },
  { dvd: 5, firstHalf: '紫微斗数·十二张案例讲义', secondHalf: '同人大有谦豫随蛊', highlights: ['十二张案例紫微在十二宫各一张', '命宫贪狼文武双全', '身宫在财帛宫为职业妇女', '阳宅化解论'] },
  { dvd: 6, firstHalf: '紫微斗数·四化星详解', secondHalf: '临观噬嗑贲剥复', highlights: ['化禄主财性守', '化权性刚代表官印', '化科主科名名气', '化忌主劫杀', '大限流年四化叠加'] },
  { dvd: 7, firstHalf: '紫微斗数·格局论(上)', secondHalf: '无妄大畜颐大过坎离', highlights: ['杀破狼格局变动开创', '火贪格主暴发', '三方四正看格局', '官禄宫最喜权星'] },
  { dvd: 8, firstHalf: '紫微斗数·格局论(下)', secondHalf: '咸恒遁大壮晋明夷', highlights: ['流年批命法', '迷津评断一生总格局', '命相同参提高准确率', '南人北相为贵相'] },
  { dvd: 9, firstHalf: '紫微斗数·大限流年', secondHalf: '家人睽蹇解损益', highlights: ['大限十年运势', '小限流年推算', '人定胜天论', '三年前化解论'] },
  { dvd: 10, firstHalf: '紫微斗数·实战案例(上)', secondHalf: '夬姤萃升困井', highlights: ['官禄化忌事业受阻', '财帛化禄财运亨通', '夫妻宫煞星婚姻不顺'] },
  { dvd: 11, firstHalf: '紫微斗数·实战案例(下)', secondHalf: '革鼎震艮渐归妹', highlights: ['疾厄宫判断健康', '结合中医子午流注', '煞星在午主心脏在丑主肝'] },
  { dvd: 12, firstHalf: '面相学·五形论详解', secondHalf: '丰旅巽兑涣节', highlights: ['木火土金水五种面相类型', '越纯越贵原则', '气色主两个礼拜', '眼神判断法'] },
  { dvd: 13, firstHalf: '面相学·气色与断命', secondHalf: '中孚小过既济未济', highlights: ['面相气色判断吉凶', '印堂日角月角', '眉毛代表六亲', '眼袋判断子女'] },
  { dvd: 14, firstHalf: '推命学·子平法入门', secondHalf: '64卦综合应用(上)', highlights: ['子平法四柱八字排列', '天干地支五行属性', '十神体系'] },
  { dvd: 15, firstHalf: '推命学·大运流年', secondHalf: '64卦综合应用(下)', highlights: ['大运排列', '流年推演', '卦象在实际生活中的应用'] },
  { dvd: 16, firstHalf: '测字术·拆字会意法', secondHalf: '占卜实战·起卦法', highlights: ['拆字法分解偏旁', '会意法联想推断', '揲蓍法', '金钱卦'] },
  { dvd: 17, firstHalf: '测字术·实战案例', secondHalf: '六爻断事技巧', highlights: ['测字时机和环境', '六神占断', '用神取用'] },
  { dvd: 18, firstHalf: '堪舆学·峦头论(上)', secondHalf: '龙穴砂水基础', highlights: ['山形水势判断', '龙脉走势与气脉', '穴位藏风聚气'] },
  { dvd: 19, firstHalf: '堪舆学·峦头论(下)', secondHalf: '罗盘使用与理气', highlights: ['砂手环抱', '水口进出', '罗盘方位测量', '九星飞布原理'] },
  { dvd: 20, firstHalf: '堪舆学·阳宅风水', secondHalf: '三吉六秀·天星四贵', highlights: ['房屋坐向选择', '室内方位安排', '三吉方向', '六秀方向好砂则吉'] },
  { dvd: 21, firstHalf: '堪舆学·阴宅风水', secondHalf: '八煞黄泉·城局九星', highlights: ['八煞黄泉绝对禁忌', '天星四贵', '城局形势判断', '来龙朝山砂势'] },
  { dvd: 22, firstHalf: '堪舆学·2/3大于1/3', secondHalf: '风水改运实例', highlights: ['人事+地理=2/3>天命1/3', '好风水有鱼虾龟', '床位朝向决定生子性别'] },
  { dvd: 23, firstHalf: '综合应用·命相卜术结合', secondHalf: '天纪在生活中的实践', highlights: ['紫微+面相+易经综合判断', '天地人三纪统一观', '倪师批命实战示范'] },
  { dvd: 24, firstHalf: '天纪总结·核心心法', secondHalf: '传承与期许', highlights: ['天纪精神总结', '命运掌握在自己手上', '文化传承使命', '不希望中华文化失传'] },
];

// ─── 倪师天纪核心语录库 ──────────────────────────────────
export const TIANJI_QUOTES = [
  { text: '文字只是协助诸位到达真理的彼岸，千万不要三个月以后，怎么还是扛着船在马路上跑', topic: '学习态度' },
  { text: '大道至简——飞星飞来飞去太复杂，不搞这个', topic: '紫微斗数' },
  { text: '命宫为本，三方为用——命宫主星决定基本格局与天生性格，三方决定用武之地', topic: '紫微斗数' },
  { text: '身宫在财帛宫的女孩子，一般来说就是职业妇女', topic: '紫微斗数' },
  { text: '最怕的是七杀临身，七杀临身的人一辈子多败少成', topic: '紫微斗数' },
  { text: '官禄宫最喜欢权星入进来', topic: '紫微斗数' },
  { text: '算命就是一个讨论果的哲学', topic: '命学哲理' },
  { text: '命是天注定的，运掌握在我们自己手上', topic: '命学哲理' },
  { text: '三年前有办法化解，到了时候再改都是事后。碗打破了我们再去解', topic: '命学哲理' },
  { text: '祸福无门，咎由自取', topic: '命学哲理' },
  { text: '看到外面，就知道里面藏了什么', topic: '面相' },
  { text: '看相最难看的就是气色。气色主两个礼拜', topic: '面相' },
  { text: '越纯越贵——五形越纯正的面相类型越贵', topic: '面相' },
  { text: '南人北相、北人南相是贵相的重要标志', topic: '面相' },
  { text: '害的到你的叫做小人。会影响到你的叫做小人', topic: '识人' },
  { text: '眼珠闪动主心术不正，四白眼主横死，三角眼主心生毒计', topic: '面相' },
  { text: '人事的努力加上地理上的调整，一定能大于先天的命运', topic: '堪舆' },
  { text: '好的风水地方要有鱼虾龟——生气充沛的标志', topic: '堪舆' },
  { text: '八煞黄泉是坟墓和阳宅立向的绝对禁忌', topic: '堪舆' },
  { text: '唯有紫微斗数可以把天文和地理两个融合在一起', topic: '紫微斗数' },
  { text: '如果读了易经，越弄越复杂，就是没有读通易经', topic: '易经' },
  { text: '不疑何卜——只有有疑虑时才占卜', topic: '易经' },
  { text: '外象一直在变，但精神是一样的', topic: '易经' },
  { text: '爸爸住爸爸位置，儿子住儿子位置，叫做名位相等', topic: '堪舆' },
  { text: '中国五百年出一个天官，现在还不到五百年', topic: '天文' },
  { text: '煞星通过疾厄宫在午主心脏，在丑主肝', topic: '紫微斗数' },
  { text: '我不希望这些中华文化失传，所以就教了许多学生', topic: '传承' },
  { text: '命相同参会提高准确率', topic: '综合' },
  { text: '天纪就是自然法则，是真理', topic: '天纪总论' },
];

// ─── 统计 ────────────────────────────────────────────────
export const TIANJI_STATS = {
  totalModules: TIANJI_MODULES.length,
  activeModules: TIANJI_MODULES.filter(m => m.status === 'active').length,
  totalChapters: TIANJI_MODULES.reduce((sum, m) => sum + m.chapters.length, 0),
  totalHexagrams: HEXAGRAMS.length,
  totalFengShui: FENGSHUI_ENTRIES.length,
  totalEpisodes: TIANJI_EPISODES.length,
  totalQuotes: 29,
  videoHours: 48,
  videoEpisodes: 24,
  hdEpisodes: 83,
  recordYear: 1994,
  lectureBooks: ['天机道', '人间道', '地脉道', '64卦易图'],
  schools: ['三合派（紫微斗数）', '象数派（易经）', '九星派（堪舆）', '河洛数理派（推命）'],
};
